let channelOffset=0;
const channelStatusNames={eligible:'Active reactor',paused:'Paused',retired:'Retired / unavailable',official:'Official performer',review:'Needs review',other:'Other / outside coverage'};
async function loadChannelUpdates(){if(!communityState?.moderator)return;try{
 const r=await performerApi('/channels?q='+encodeURIComponent($('channelSearch').value)+'&unavailable='+Number($('channelUnavailable').checked)+'&offset='+channelOffset);
 $('channelList').innerHTML=r.items.map(c=>`<article class="review-item"><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.id)} · ${escapeHtml(channelStatusNames[c.discovery_scope]||c.discovery_scope)}</p><p>Last checked: ${c.recent_checked_at?prettyDate(c.recent_checked_at):'Not checked'}${c.recent_failures?' · '+c.recent_failures+' consecutive failures':''}</p>${c.recent_error?`<p>${escapeHtml(c.recent_error)} · Retry: ${c.recent_retry_at?prettyDate(c.recent_retry_at):'Ready'}</p>`:''}<a href="https://www.youtube.com/channel/${escapeHtml(c.id)}" target="_blank" rel="noopener">Check on YouTube ↗</a><button class="outline-button" data-channel-edit="${escapeHtml(c.id)}">Edit name / status</button><button class="outline-button" data-channel-retry="${escapeHtml(c.id)}" ${c.discovery_scope!=='eligible'?'disabled':''}>Queue retry</button></article>`).join('')||'<p>No channels found.</p>';
 $('channelPrevious').disabled=channelOffset===0;$('channelNext').disabled=!r.hasMore;
 $('channelList').querySelectorAll('[data-channel-edit]').forEach(b=>b.onclick=()=>{const c=r.items.find(c=>c.id===b.dataset.channelEdit),f=$('channelForm');f.elements.channelId.value=c.id;f.elements.name.value=c.name;f.elements.status.value=c.discovery_scope;f.elements.note.value='';f.scrollIntoView({block:'start'});f.elements.note.focus();});
 $('channelList').querySelectorAll('[data-channel-retry]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const r=await performerApi('/channels/retry',{channelId:b.dataset.channelRetry,note:'Moderator requested a fresh availability check'});$('channelListStatus').textContent=r.message;await loadChannelUpdates();}catch(e){$('channelListStatus').textContent=e.message;b.disabled=false;}});
 }catch(e){$('channelListStatus').textContent=e.message;}}
$('channelForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{const r=await performerApi('/channels/save',{channelId:f.elements.channelId.value,name:f.elements.name.value,status:f.elements.status.value,note:f.elements.note.value});$('channelSaveStatus').textContent=r.message;await loadChannelUpdates();}catch(e){$('channelSaveStatus').textContent=e.message;}finally{b.disabled=false;}};
$('channelRefresh').onclick=$('channelUnavailable').onchange=()=>{channelOffset=0;loadChannelUpdates();};
$('channelPrevious').onclick=()=>{channelOffset=Math.max(0,channelOffset-50);loadChannelUpdates();};$('channelNext').onclick=()=>{channelOffset+=50;loadChannelUpdates();};
window.addEventListener('reaction-auth-change',()=>{$('channelList').replaceChildren();$('channelForm').reset();$('channelSaveStatus').textContent='';$('channelListStatus').textContent='';channelOffset=0;});
