let classificationOffset=0,memberOffset=0;
async function loadLaunchReview(){
 if(!communityState?.moderator)return;
 let panel=$('launchReview');
 if(!panel){panel=document.createElement('div');panel.id='launchReview';panel.className='panel';$('member-review').append(panel);
 panel.innerHTML='<h2>Member review</h2><p>Novice: fewer than 25 points. Contributor: 25 points. Higher existing badges continue at 100, 250 and 1,000 points. Mutes stop posting for 24 hours and allow browsing. Trusted Member is separate from points and badges. Review members with three moderator-approved contributions, check their accuracy and quality, then grant trust or keep approval required. Trust can be revoked with a reason.</p><label>Trust filter <select id="memberTrustFilter"><option value="all">All members</option><option value="ready">Ready for trust review</option><option value="trusted">Trusted members</option></select></label><label>Search names or email <input id="memberSearch" maxlength="100"></label><button id="memberRefresh" class="outline-button">Search / refresh</button><div id="memberItems"></div><button id="memberPrevious" class="outline-button">Previous 100</button><button id="memberNext" class="outline-button">Next 100</button><p id="memberReviewStatus" role="status"></p>';
 $('memberTrustFilter').onchange=()=>{memberOffset=0;loadMembers();};
 $('memberRefresh').onclick=()=>{memberOffset=0;loadMembers();};
 $('memberPrevious').onclick=()=>{memberOffset=Math.max(0,memberOffset-100);loadMembers();};
 $('memberNext').onclick=()=>{memberOffset+=100;loadMembers();};
 }
 await loadMembers();
}
async function loadClassificationReview(){
 if(!communityState?.moderator)return;
 let panel=$('classificationReviewPanel');
 if(!panel){panel=document.createElement('div');panel.id='classificationReviewPanel';panel.className='panel';$('classification-review').append(panel);
 panel.innerHTML='<h2>Video classification review</h2><p>Verify the reaction on YouTube, choose its format, then confirm. Unknown describes format; Probable describes reaction confidence. Excluded and unavailable videos stay outside these lists.</p><label>List <select id="classificationGroup"><option value="unknown">Unknown format</option><option value="probable">Probable reactions</option></select></label><button id="classificationRefresh" class="outline-button">Refresh list</button><div id="classificationItems"></div><button id="classificationPrevious" class="outline-button">Previous 50</button><button id="classificationNext" class="outline-button">Next 50</button><p id="classificationStatus" role="status"></p>';
 $('classificationGroup').onchange=$('classificationRefresh').onclick=()=>{classificationOffset=0;loadClassification();};
 $('classificationPrevious').onclick=()=>{classificationOffset=Math.max(0,classificationOffset-50);loadClassification();};
 $('classificationNext').onclick=()=>{classificationOffset+=50;loadClassification();};
 }
 installVideoCorrectionPanel();
 await loadClassification();
}
async function loadClassification(){try{
 const r=await performerApi('/classification?group='+$('classificationGroup').value+'&offset='+classificationOffset);
 $('classificationItems').innerHTML=r.items.map(v=>`<form class="review-item" data-classify="${escapeHtml(v.id)}"><h3>${escapeHtml(v.title)}</h3><p>${escapeHtml(v.channel_name||'Unknown channel')} · ${escapeHtml(v.status)} · ${escapeHtml(v.format)}</p><a href="https://www.youtube.com/watch?v=${escapeHtml(v.id)}" target="_blank" rel="noopener">Check on YouTube ↗</a><label>Format <select name="format"><option value="">Choose format</option><option value="SHORT" ${v.format==='SHORT'?'selected':''}>Short</option><option value="FULL_LENGTH" ${v.format==='FULL_LENGTH'?'selected':''}>Full-length</option></select></label><label><input type="checkbox" name="verified" required> I verified this is a Missioned Souls reaction</label><button class="outline-button">Confirm reaction &amp; save format</button><button type="button" class="outline-button" data-classification-reject>Reject / remove video</button><p role="status"></p></form>`).join('')||'<p>No matching videos.</p>';
 $('classificationPrevious').disabled=classificationOffset===0;$('classificationNext').disabled=!r.hasMore;
 $('classificationItems').querySelectorAll('form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{const r=await performerApi('/classification/confirm',{videoId:f.dataset.classify,format:f.elements.format.value});$('classificationStatus').textContent=r.message;await loadClassification();await reloadMemberCatalog();}catch(err){f.querySelector('[role=status]').textContent=err.message;}finally{b.disabled=false;}});
 $('classificationItems').querySelectorAll('[data-classification-reject]').forEach(b=>b.onclick=async()=>{
 const f=b.closest('form');if(!confirm('Remove this video from the catalog and review lists? Future discovery will respect this exclusion.'))return;
 f.querySelectorAll('button').forEach(x=>x.disabled=true);
 try{const r=await performerApi('/review',{id:'missioned-souls',videos:[f.dataset.classify],decision:'exclude'});$('classificationStatus').textContent=r.message;await loadClassification();await reloadMemberCatalog();}
 catch(e){f.querySelector('[role=status]').textContent=e.message;f.querySelectorAll('button').forEach(x=>x.disabled=false);}
 });
 }catch(e){$('classificationStatus').textContent=e.message;}}
async function loadMembers(){try{
 const r=await communityApi('/users?q='+encodeURIComponent($('memberSearch').value)+'&trust='+$('memberTrustFilter').value+'&offset='+memberOffset);
 $('memberItems').innerHTML=r.items.map(m=>`<form class="review-item" data-member="${escapeHtml(m.id)}"><h3>${memberDisplayName(m.name||'Display name not set',m.points)} · ${escapeHtml(m.tier)}${m.moderator?' · Moderator':''}</h3><p>${escapeHtml(m.email||'Email recorded on next visit')} · ${m.points} Contribution Points · ${m.trusted?'Trusted Member':'Approval required'} · ${m.approved_count} moderator-approved contributions${m.trustReviewReady?' · Ready for trust review':''}</p><details><summary>Review contributions and trust history</summary><button type="button" class="outline-button" data-member-evidence>Load evidence</button><div data-member-evidence-content></div></details><p>Joined: ${prettyDate(m.created_at)} · Last seen: ${m.last_seen_at?prettyDate(m.last_seen_at):'Not recorded'}${m.muted_until&&Date.parse(m.muted_until)>Date.now()?' · Muted until '+prettyDate(m.muted_until):''}</p><label>Action <select name="action"><option value="name">Correct display name</option><option value="grant-trust" ${m.approved_count<3||m.trusted?'disabled':''}>Grant Trusted Member status</option><option value="revoke-trust" ${!m.trusted?'disabled':''}>Revoke Trusted Member status</option><option value="defer-trust" ${m.trusted?'disabled':''}>Reviewed: keep approval required</option><option value="points">Adjust points</option><option value="mute">Mute posting for 24 hours</option><option value="unmute">Remove posting mute</option></select></label><label>Display name <input name="name" maxlength="40" value="${escapeHtml(m.name)}"></label><label>Point adjustment (+ or −) <input name="amount" type="number" step="1" min="-1000" max="1000" value="0"></label><label>Reason <input name="note" minlength="5" maxlength="500" required></label><button class="outline-button">Save member change</button><p role="status"></p></form>`).join('')||'<p>No members found.</p>';
 $('memberPrevious').disabled=memberOffset===0;$('memberNext').disabled=!r.hasMore;
 $('memberItems').querySelectorAll('[data-member-evidence]').forEach(b=>b.onclick=async()=>{
  b.disabled=true;const content=b.closest('details').querySelector('[data-member-evidence-content]');
  try{const r=await communityApi('/users/contributions?id='+encodeURIComponent(b.closest('form').dataset.member));
   content.innerHTML='<p>Latest 100 contributions. Only accepted contributions verified by another moderator count toward trust review.</p>'+r.items.map(c=>`<article class="contribution"><strong>${escapeHtml(c.kind)} · ${escapeHtml(c.status)}</strong><p>${escapeHtml(c.body)}</p><a href="https://www.youtube.com/watch?v=${escapeHtml(c.video_id)}" target="_blank" rel="noopener">Check video ↗</a><p>${escapeHtml(c.review_note||'No moderator review recorded')} · ${c.reviewed_at?prettyDate(c.reviewed_at):'Unreviewed'}</p></article>`).join('')+'<h4>Trust history</h4>'+r.trustHistory.map(h=>`<p>${prettyDate(h.created_at)} · ${h.trusted?'Trusted Member':'Approval required'} · ${escapeHtml(h.reason)}</p>`).join('');
  }catch(e){content.textContent=e.message;}finally{b.disabled=false;}
 });
 $('memberItems').querySelectorAll('form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('button');b.disabled=true;try{const r=await communityApi('/users/update',{id:f.dataset.member,action:f.elements.action.value,name:f.elements.name.value,amount:Number(f.elements.amount.value),note:f.elements.note.value});$('memberReviewStatus').textContent=r.message;await loadMembers();await loadCommunity();}catch(err){f.querySelector('[role=status]').textContent=err.message;}finally{b.disabled=false;}});
 }catch(e){$('memberReviewStatus').textContent=e.message;}}
window.addEventListener('reaction-auth-change',()=>{$('launchReview')?.remove();$('classificationReviewPanel')?.remove();$('videoCorrectionPanel')?.remove();$('classificationReviewNav').hidden=true;$('moderatorNavSection').hidden=true;});

function installVideoCorrectionPanel(){
 if($('videoCorrectionPanel'))return;
 const panel=document.createElement('div');panel.id='videoCorrectionPanel';panel.className='panel';$('classification-review').prepend(panel);
 panel.innerHTML='<h2>Correct video information</h2><p>Fix a video before or after approval. Paste its YouTube link, load the saved details, then fetch the correct title and channel from YouTube. Save Corrections keeps review decisions. Save Corrections &amp; Restore removes the Missioned Souls exclusion and confirms the match. Comments and ratings are retained.</p><form id="videoCorrectionLookup"><label>YouTube video link or ID<input name="video" required maxlength="250"></label><button class="outline-button">Load video</button></form><div id="videoCorrectionEditor"></div><p id="videoCorrectionStatus" role="status"></p>';
 $('videoCorrectionLookup').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;$('videoCorrectionEditor').replaceChildren();try{
 const r=await communityApi('/catalog-video?video='+encodeURIComponent(e.target.elements.video.value.trim())),v=r.video;
 $('videoCorrectionStatus').textContent='Loaded saved details. Fetch YouTube details to verify the correct channel.';
 $('videoCorrectionEditor').innerHTML=`<form id="videoCorrectionForm"><p><strong>Catalog status:</strong> ${escapeHtml(r.decision?.status||'No Missioned Souls match')} · ${v.available===1?'Available':'Unavailable'}</p>${r.decision?.exclusionReason?`<p><strong>Exclusion reason:</strong> ${escapeHtml(r.decision.exclusionReason)}</p>`:''}<a href="https://www.youtube.com/watch?v=${escapeHtml(v.id)}" target="_blank" rel="noopener">Verify on YouTube ↗</a><button type="button" class="outline-button" id="videoCorrectionFetch">Fetch YouTube details</button><label>Video title<input name="title" maxlength="250" required value="${escapeHtml(v.title)}"></label><label>Channel name<input name="channelName" maxlength="100" required value="${escapeHtml(v.channelName||'')}"></label><label>Channel ID<input name="channelId" required value="${escapeHtml(v.channel_id)}"></label><label>Upload date<input name="publishedAt" type="date" value="${escapeHtml(v.published_at?.slice(0,10)||'')}"></label><label>Format<select name="format">${['UNKNOWN','FULL_LENGTH','SHORT'].map(f=>`<option value="${f}" ${v.format===f?'selected':''}>${f==='FULL_LENGTH'?'Full-length':f==='SHORT'?'Short':'Unknown'}</option>`).join('')}</select></label><label>Reason for correction or restoration<textarea name="note" required minlength="5" maxlength="500"></textarea></label><button class="primary-button" type="submit">Save Corrections</button> <button class="outline-button" type="submit" name="restore" value="true" ${!r.decision?.status||v.available!==1||r.decision?.performerStatus!=='active'?'disabled':''}>Save Corrections &amp; Restore</button><p class="subtle">Restore explicitly reverses the Missioned Souls rejection/exclusion and confirms this video. Verify it is a valid reaction and explain why it should be restored.</p><p class="subtle">When the YouTube API is configured, the saved title, channel and upload date are verified again on the server.</p></form><h3>Recent corrections</h3>${r.history.map(h=>`<p>${escapeHtml(prettyDate(h.created_at))} · ${escapeHtml(h.note)}</p>`).join('')||'<p>No previous corrections.</p>'}`;
 const form=$('videoCorrectionForm');
 $('videoCorrectionFetch').onclick=async()=>{const b=$('videoCorrectionFetch');b.disabled=true;try{const m=await communityApi('/catalog-video/metadata?video='+encodeURIComponent(v.id));for(const k of ['title','channelName','channelId'])form.elements[k].value=m[k];form.elements.publishedAt.value=m.publishedAt?.slice(0,10)||'';$('videoCorrectionStatus').textContent='YouTube details loaded. Check the format and enter a correction reason.';}catch(err){$('videoCorrectionStatus').textContent=err.message;}finally{b.disabled=false;}};
 form.onsubmit=async e=>{e.preventDefault();const restore=e.submitter?.name==='restore';form.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await communityApi('/catalog-video/update',{videoId:v.id,...Object.fromEntries(new FormData(form)),restore});await reloadMemberCatalog();$('videoCorrectionEditor').replaceChildren();$('videoCorrectionStatus').textContent=result.message;}catch(err){$('videoCorrectionStatus').textContent=err.message;}finally{form.querySelectorAll('button').forEach(b=>b.disabled=false);}};
 }catch(err){$('videoCorrectionStatus').textContent=err.message;}finally{button.disabled=false;}};
}
