import {categories,normalizeVideo,selectVideos,viewGain,classifyShort} from './missioned-souls-core.mjs';
const el=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>v==null?'—':Number(v).toLocaleString(),date=v=>v?new Date(v).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Date unknown';
let data={videos:[]},category='All videos',visible=24,editing=null;
const preview=location.pathname==='/preview.html';
const definitions=()=>data.categoryDefinitions||categories.map(id=>({id,name:id,archived:false}));
const categoryName=id=>definitions().find(c=>c.id===id)?.name||id;
function renderCategoryManager(){
 if(!data.moderator)return;
 let panel=el('ms-category-manager');
 if(!panel){panel=document.createElement('section');panel.id='ms-category-manager';el('ms-admin').append(panel);}
 panel.innerHTML='<h3>Categories</h3><form id="ms-category-add"><label>New category<input name="name" required maxlength="60"></label><button class="outline-button">Add category</button></form><div class="ms-category-rows">'+definitions().map((c,i)=>`<div class="ms-category-row"><input aria-label="Category name" value="${esc(c.name)}" maxlength="60" ${c.id==='Shorts'?'disabled':''}><span>${c.archived?'Archived':''}</span><button type="button" data-operation="rename" data-id="${esc(c.id)}" ${c.id==='Shorts'?'disabled':''}>Rename</button><button type="button" data-operation="move" data-direction="-1" data-id="${esc(c.id)}" title="Move up" aria-label="Move ${esc(c.name)} up" ${i===0?'disabled':''}>↑</button><button type="button" data-operation="move" data-direction="1" data-id="${esc(c.id)}" title="Move down" aria-label="Move ${esc(c.name)} down" ${i===definitions().length-1?'disabled':''}>↓</button><button type="button" data-operation="archive" data-archived="${!c.archived}" data-id="${esc(c.id)}" ${c.id==='Shorts'?'disabled':''}>${c.archived?'Restore':'Archive'}</button></div>`).join('')+'</div><p id="ms-category-status" role="status"></p>';
 const act=async body=>{panel.querySelectorAll('button').forEach(b=>b.disabled=true);try{if(preview)throw new Error('Category management requires the signed-in catalog.');await api({action:'categories',revision:data.categoryRevision,...body});await load();el('ms-category-status').textContent='Categories updated.';}catch(e){await load();el('ms-category-status').textContent=e.message;}};
 el('ms-category-add').onsubmit=e=>{e.preventDefault();act({operation:'add',name:e.currentTarget.elements.name.value});};
 panel.querySelectorAll('[data-operation]').forEach(b=>b.onclick=()=>act({operation:b.dataset.operation,id:b.dataset.id,name:b.parentElement.querySelector('input').value,direction:Number(b.dataset.direction),archived:b.dataset.archived==='true'}));
}
async function api(body){const r=await window.reactionAuth.fetch('/api/missioned-souls',{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Catalog request failed.');return d;}
async function load(){try{data=preview?await(await fetch('/missioned-souls-seed.json')).json():await api();data.videos=data.videos.map(v=>({...normalizeVideo(v,definitions().map(c=>c.id)),history:v.history||[]}));if(preview){data.moderator=true;const saved=localStorage.getItem('ms-preview-draft');if(saved)data=JSON.parse(saved);}el('ms-admin').hidden=!data.moderator;render();}catch(e){el('ms-status').textContent=e.message;}}
function render(){
 if(definitions().some(c=>c.id===category&&c.archived))category='All videos';
 el('ms-count').textContent=num(data.videos.filter(v=>v.available).length);el('ms-reviewed').textContent=num(data.videos.filter(v=>v.reviewed).length);el('ms-updated').textContent=data.updatedAt?date(data.updatedAt):'Not refreshed';el('ms-coverage').textContent=data.coverage||'Catalog imported. Review suggested categories before sharing.';
 el('ms-refresh-state').textContent=preview?'Local review preview. Changes are saved on this browser; export them to retain or import them later. Automatic updates are not connected in this preview.':(data.refresh?.message||'No official upload scan has run yet.')+(data.refresh?.lastCompleteAt?' Last complete scan: '+date(data.refresh.lastCompleteAt)+'.':'');
 el('ms-categories').innerHTML=['All videos',...definitions().filter(c=>!c.archived).map(c=>c.id),'Facebook only'].map(c=>`<button class="${c===category?'active':''}" data-category="${esc(c)}" aria-pressed="${c===category}">${esc(categoryName(c))}<span>${data.videos.filter(v=>v.available&&(c==='All videos'||(c==='Facebook only'?v.platform==='Facebook'&&!v.youtubeEquivalent:v.tags.includes(c)))).length}</span></button>`).join('');
 renderCategoryManager();
 el('ms-categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;visible=24;render();});
 const ranking=el('ms-ranking').value,list=selectVideos(data.videos,{category,ranking,source:el('ms-source').value,query:el('ms-search').value,includeShorts:el('ms-shorts').checked});
 el('ms-heading').textContent=categoryName(category);el('ms-results').textContent=list.length+' matching video'+(list.length===1?'':'s');
 el('ms-ranking-note').textContent=['day','week','month'].includes(ranking)?'Ranked by observed views gained over '+({day:'24 hours',week:'7 days',month:'30 days'}[ranking])+'. Videos need a recent statistic and a baseline within 6 hours of the period boundary.':ranking==='recent'?'The ten newest dated videos in the current selection. Unknown dates are excluded.':['views','likes','comments'].includes(ranking)?'Ranked by the latest recorded '+ranking+'. Missing statistics are excluded. Check the recorded date on each card.':'Newest first. Videos with unknown dates appear at the end.';
 el('ms-grid').innerHTML=list.length?list.slice(0,visible).map((v,i)=>`<article class="ms-card"><a class="ms-thumb" href="${esc(v.url)}" target="_blank" rel="noopener noreferrer" aria-label="Watch ${esc(v.title)}">${v.youtubeId?`<img loading="lazy" alt="" src="https://i.ytimg.com/vi/${esc(v.youtubeId)}/hqdefault.jpg">`:esc(v.platform)+' video'}</a><div class="ms-card-body"><p>${ranking!=='latest'?'#'+(i+1)+' · ':''}${esc(v.platform)} · ${date(v.publishedAt)}</p><h3>${esc(v.title)}</h3><div class="ms-tags">${v.tags.map(t=>`<span>${esc(categoryName(t))}</span>`).join('')}</div><p>${v.reviewed?'Categories reviewed':'Category review pending'}</p><p>${num(v.views)} views · ${num(v.likes)} likes · ${num(v.comments)} comments<br>Statistics: ${v.statsAt?date(v.statsAt):'not recorded'}${['day','week','month'].includes(ranking)?'<br>'+num(viewGain(v,{day:1,week:7,month:30}[ranking]))+' views gained':''}</p><a href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">Watch on ${esc(v.platform)} ↗</a>${data.moderator?`<button class="outline-button" data-short="${esc(v.id)}" aria-pressed="${v.tags.includes('Shorts')}">${v.tags.includes('Shorts')?'Remove Shorts tag':'Mark as Short'}</button><button class="outline-button" data-edit="${esc(v.id)}">Review categories & details</button>`:''}</div></article>`).join(''):'<div class="ms-empty"><h3>No videos to show yet</h3><p>'+(['day','week','month'].includes(ranking)?'This ranking needs view history. Continue regular refreshes, or import dated statistics.':'Try another section, change filters, or import more videos into the catalog.')+'</p></div>';
 el('ms-grid').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(data.videos.find(v=>v.id===b.dataset.edit)));el('ms-grid').querySelectorAll('[data-short]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const video=data.videos.find(v=>v.id===b.dataset.short),isShort=!video.tags.includes('Shorts');const result=preview?await save({action:'save',video:classifyShort(video,isShort)}):await api({action:'set-short',id:video.id,isShort});if(!preview)await load();el('ms-status').textContent=result.message;}catch(error){el('ms-status').textContent=error.message;}finally{b.disabled=false;}});el('ms-more').hidden=list.length<=visible;
}
function edit(v=null){editing=v;const f=el('ms-form');f.reset();for(const key of ['title','url','views','likes','comments','sourceNote'])f.elements[key].value=v?.[key]??'';for(const key of ['publishedAt','statsAt']){const d=v?.[key]?new Date(v[key]):null;f.elements[key].value=d?new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16):'';}for(const key of ['reviewed','youtubeEquivalent','available'])f.elements[key].checked=v?!!v[key]:key==='available';f.elements.isShort.checked=v?.tags.includes('Shorts')||false;el('ms-tag-options').innerHTML=definitions().filter(c=>c.id!=='Shorts'&&(!c.archived||v?.tags.includes(c.id))).map(c=>c.id).map(t=>`<label><input type="checkbox" name="tags" value="${esc(t)}" ${v?.tags.includes(t)?'checked':''}>${esc(categoryName(t))}</label>`).join('');el('ms-form-status').textContent='';el('ms-editor').showModal();}
async function save(body){if(preview){const items=body.action==='save'?[body.video]:body.videos;if(!Array.isArray(items)||!items.length||items.length>1000)throw new Error('Import 1–1000 videos per file.');const next=items.map(v=>normalizeVideo(v,definitions().map(c=>c.id)));for(const v of next){const old=data.videos.find(x=>x.id===v.id);v.history=[...(old?.history||[])];if(v.statsAt&&v.views!=null){v.history=v.history.filter(h=>h.at.slice(0,10)!==v.statsAt.slice(0,10));v.history.push({at:v.statsAt,views:v.views});}data.videos=data.videos.filter(x=>x.id!==v.id);data.videos.push(v);}data.updatedAt=new Date().toISOString();localStorage.setItem('ms-preview-draft',JSON.stringify(data));render();return {message:next.length+' videos saved to local preview.'};}const d=await api(body);await load();return d;}
el('ms-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,button=f.querySelector('button[type=submit],button.primary-button');button.disabled=true;try{const v={};for(const key of ['title','url','views','likes','comments','sourceNote'])v[key]=f.elements[key].value;for(const key of ['publishedAt','statsAt'])v[key]=f.elements[key].value?new Date(f.elements[key].value).toISOString():null;for(const key of ['reviewed','youtubeEquivalent','available'])v[key]=f.elements[key].checked;v.tags=[...f.querySelectorAll('[name=tags]:checked')].map(x=>x.value);if(v.tags.some(t=>t.endsWith('Vlogs'))&&!v.tags.includes('All Vlogs'))v.tags.push('All Vlogs');v.shortsOverride=f.elements.isShort.checked;if(v.shortsOverride)v.tags.push('Shorts');if(editing&&normalizeVideo(v,definitions().map(c=>c.id)).id!==editing.id)throw new Error('Keep the same video URL when editing. Add a separate record for a different video.');const r=await save({action:'save',video:v});el('ms-status').textContent=r.message;el('ms-editor').close();}catch(error){el('ms-form-status').textContent=error.message;}finally{button.disabled=false;}};
for(const id of ['ms-search','ms-source','ms-ranking','ms-shorts'])el(id).addEventListener(id==='ms-search'?'input':'change',()=>{visible=24;render();});el('ms-more').onclick=()=>{visible+=24;render();};el('ms-close').onclick=()=>el('ms-editor').close();el('ms-add').onclick=()=>edit();
el('ms-refresh').onclick=async()=>{if(preview){el('ms-status').textContent='Use the Python seed script or import catalog JSON in this offline preview. Live refresh will use the server’s YouTube API key after deployment.';return;}el('ms-refresh').disabled=true;try{const r=await api({action:'refresh'});await load();el('ms-status').textContent=r.message;}catch(e){el('ms-status').textContent=e.message;}finally{el('ms-refresh').disabled=false;}};
el('ms-import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw new Error('File must be under 2 MB.');const input=JSON.parse(await file.text());const r=await save({action:'import',videos:Array.isArray(input)?input:input.videos});el('ms-status').textContent=r.message;}catch(error){el('ms-status').textContent=error.message;}finally{e.target.value='';}};
el('ms-export').onclick=()=>{const blob=new Blob([JSON.stringify({...data,moderator:undefined},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='missioned-souls-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
if(preview)load();else{window.reactionAuth.ready.then(()=>{if(window.reactionAuth.account?.id)load();});window.addEventListener('reaction-auth-change',()=>{if(window.reactionAuth.account?.id)load();else{data={videos:[]};el('ms-grid').replaceChildren();el('ms-admin').hidden=true;}});}
