import {candidates} from './reconciliation-candidates.mjs';
const form=document.getElementById('workbookImportForm');
if(form){
 const panel=document.createElement('section');panel.className='panel';panel.innerHTML='<h2>Reconcile missing reaction videos</h2><p>Check up to 100 video IDs against current YouTube metadata. Clear matches are confirmed; uncertain reactions go to review. Existing decisions and exclusions are preserved.</p><button type="button" class="outline-button" id="reconcileLoad">Load 74 audited missing IDs</button><p>For future batches, enter one video ID and channel ID per line, separated by a comma.</p><textarea id="reconcileInput" rows="8" aria-label="Video and channel IDs"></textarea><p><button type="button" class="primary-button" id="reconcileRun">Check and reconcile</button> <button type="button" class="outline-button" id="reconcileHistory">Recent receipts</button></p><p id="reconcileStatus" role="status"></p><div id="reconcileResults"></div>';
 form.parentElement.append(panel);
 const el=id=>document.getElementById(id);let busy=false,generation=0;
 const controls=()=>{for(const id of ['reconcileRun','reconcileLoad','reconcileHistory','reconcileInput'])el(id).disabled=busy;};
 const api=async body=>{const response=await reactionAuth.fetch('/api/reconciliation',{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Reconciliation unavailable.');return data;};
 function show(receipt){const box=document.createElement('section'),heading=document.createElement('h3');heading.textContent='Receipt · '+receipt.at;box.append(heading);const list=document.createElement('ul');for(const r of receipt.results){const li=document.createElement('li'),a=document.createElement('a');a.href='https://www.youtube.com/watch?v='+encodeURIComponent(r.id);a.target='_blank';a.rel='noopener';a.textContent=r.title;li.append(a,document.createTextNode(' · '+r.outcome+(r.status?' · '+r.status:'')+' · '+(r.reason||'')));list.append(li);}box.append(list);const button=document.createElement('button');button.className='outline-button';button.textContent='Download receipt';button.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(receipt,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Reaction_Journey_Reconciliation_'+receipt.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};box.append(button);el('reconcileResults').append(box);}
 el('reconcileLoad').onclick=()=>{el('reconcileInput').value=candidates.map(r=>r.id+','+r.channelId).join('\n');};
 el('reconcileRun').onclick=async()=>{if(busy||!communityState?.moderator)return;busy=true;controls();const turn=generation;el('reconcileStatus').textContent='Checking videos and reconciling the live catalog…';try{const rows=el('reconcileInput').value.trim().split(/\n+/).filter(Boolean).map(line=>{const parts=line.trim().split(/[\s,]+/);if(parts.length!==2)throw new Error('Use video ID,channel ID on each line.');return {id:parts[0],channelId:parts[1]};});const result=await api({candidates:rows});if(turn!==generation)return;el('reconcileResults').replaceChildren();show(result);el('reconcileStatus').textContent=result.results.filter(r=>r.outcome==='added').length+' added. Existing decisions preserved.';await reloadMemberCatalog();}catch(e){if(turn===generation)el('reconcileStatus').textContent=e.message;}finally{busy=false;controls();}};
 el('reconcileHistory').onclick=async()=>{if(busy||!communityState?.moderator)return;busy=true;controls();const turn=generation;try{const data=await api();if(turn!==generation)return;el('reconcileResults').replaceChildren();data.items.forEach(show);el('reconcileStatus').textContent=data.items.length?'Recent reconciliation receipts.':'No reconciliations yet.';}catch(e){if(turn===generation)el('reconcileStatus').textContent=e.message;}finally{busy=false;controls();}};
 window.addEventListener('reaction-auth-change',()=>{generation++;el('reconcileResults').replaceChildren();el('reconcileInput').value='';el('reconcileStatus').textContent='';});
}
