import './reconciliation-ui.mjs';
import readXlsxFile from 'read-excel-file/browser';
import {workbookPayload} from './workbook-import-data.mjs';
(()=>{
 const el=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let current=null,busy=false,generation=0;
 const api=async(path,body)=>{const response=await reactionAuth.fetch('/api/workbook-import'+path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Import unavailable.');return data;};
 function controls(){el('workbookPreviewButton').disabled=busy;el('workbookApplyButton').disabled=busy||!current;el('workbookFile').disabled=busy;}
 function detail(rows){return '<div class="table-wrap"><table class="feed-table"><thead><tr><th>Video</th><th>Result</th><th>Status / reason</th></tr></thead><tbody>'+rows.map(v=>`<tr><td><a href="https://www.youtube.com/watch?v=${esc(v.id)}" target="_blank" rel="noopener">${esc(v.title)}</a><small> · ${esc(v.channel_name||v.id)}</small></td><td>${esc({add:'Add',existing:'Already present',excluded:'Excluded / rejected',protected:'Unavailable, held channel, or ID conflict'}[v.disposition]||v.disposition)}</td><td>${esc(v.reason||v.exclusion_reason||v.existingStatus||v.existing_status||(v.status||v.import_status)==='PENDING'&&'Needs moderator review'||v.status||v.import_status)}</td></tr>`).join('')+'</tbody></table></div>';}
 function download(data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Reaction_Journey_Import_Receipt.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function channelDetail(rows){const added=(rows||[]).filter(c=>c.disposition==='add');return added.length?'<details><summary>New channels ('+added.length+')</summary><ul>'+added.map(c=>'<li>'+esc(c.name)+' · '+esc(c.id)+'</li>').join('')+'</ul></details>':'';}
 function receipt(data){const r=data.receipt,added=r.videos.filter(v=>v.disposition==='add'),excluded=r.videos.filter(v=>v.disposition==='excluded');el('workbookResult').innerHTML=`<h2>Import receipt</h2><p>${r.channelsAdded} channels added · ${r.channelsExisting} channels already present · ${added.length} reaction matches added · ${excluded.length} excluded / rejected · ${added.filter(v=>v.status==='PENDING').length} sent for review.</p>${channelDetail(r.channels)}${detail(r.videos)}<button id="workbookReceiptDownload" class="outline-button">Download receipt</button>`;el('workbookReceiptDownload').onclick=()=>download(data);}
 window.loadWorkbookHistory=async()=>{if(!communityState?.moderator)return;try{const data=await api('/history');el('workbookHistory').innerHTML=data.items.map(j=>`<div class="panel"><strong>${esc(j.filename)}</strong><p>${esc(j.sheet)} · ${esc(j.status)} · ${esc(prettyDate(j.applied_at||j.created_at))}</p>${j.receipt?`<button class="outline-button" data-receipt="${esc(j.id)}">View receipt</button>`:'Upload again to create a fresh preview.'}</div>`).join('')||'<p>No imports yet.</p>';el('workbookHistory').querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>{current=null;controls();receipt({id:b.dataset.receipt,receipt:data.items.find(j=>j.id===b.dataset.receipt).receipt});});}catch(e){el('workbookHistory').textContent=e.message;}};
 el('workbookImportForm').onsubmit=async event=>{event.preventDefault();if(busy)return;const file=el('workbookFile').files[0];if(!file)return;current=null;busy=true;controls();const turn=++generation;el('workbookResult').replaceChildren();el('workbookImportStatus').textContent='Reading workbook and comparing with the catalog…';try{if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('Choose an .xlsx workbook.');if(file.size>10000000)throw new Error('Choose a workbook smaller than 10 MB.');const sheets=await readXlsxFile(file);const payload=workbookPayload(sheets,file.name);const data=await api('/preview',payload);if(turn!==generation)return;current=data;const c=data.counts;el('workbookResult').innerHTML=`<h2>Import preview</h2><p>${esc(data.sheet)} · ${data.channels.length} channels · ${data.videos.length} accepted video IDs.</p><p>${c.channelsAdded} new channels · ${c.channelsExisting} already present<br>${c.videosAdded} new reaction matches · ${c.videosExisting} already present · ${c.videosExcluded} excluded / rejected · ${c.videosProtected} protected · ${c.review} need review.</p><p>${data.omitted} workbook rows omitted · ${data.duplicates} identical duplicate rows removed.</p>${channelDetail(data.channels)}${detail(data.videos)}`;el('workbookImportStatus').textContent='Preview ready. Applying will compare with the live catalog again.';}catch(e){if(turn===generation)el('workbookImportStatus').textContent=e.message;}finally{busy=false;controls();}};
 el('workbookApplyButton').onclick=async()=>{if(!current||busy)return;busy=true;controls();const turn=generation;el('workbookImportStatus').textContent='Applying new records…';try{const result=await api('/apply',{id:current.id});if(turn!==generation)return;current=null;receipt(result);el('workbookImportStatus').textContent='Import complete. Existing decisions and exclusions were preserved.';await loadWorkbookHistory();await reloadMemberCatalog();}catch(e){if(turn===generation)el('workbookImportStatus').textContent=e.message;}finally{busy=false;controls();}};
 el('workbookFile').onchange=()=>{generation++;current=null;el('workbookResult').replaceChildren();el('workbookImportStatus').textContent='';controls();};
 window.addEventListener('reaction-auth-change',()=>{generation++;current=null;el('workbookResult').replaceChildren();el('workbookHistory').replaceChildren();el('workbookImportStatus').textContent='';controls();});controls();
})();

