-- Query optimization only: no video classification or moderation decisions are changed.
CREATE INDEX IF NOT EXISTS rs_matches_status_performer_video ON matches(status,performer_id,video_id);
CREATE INDEX IF NOT EXISTS rs_matches_performer_status_video ON matches(performer_id,status,video_id);
CREATE INDEX IF NOT EXISTS rs_channels_checked ON channels(checked_at);
CREATE INDEX IF NOT EXISTS rs_runs_status_finished ON runs(status,finished_at DESC);
CREATE INDEX IF NOT EXISTS rs_room_members_room_seen ON room_members(room,seen_at);
CREATE INDEX IF NOT EXISTS rs_chat_room_status_date ON chat_messages(room,status,created_at);
CREATE INDEX IF NOT EXISTS rs_comment_likes_comment ON comment_likes(comment_id);
CREATE INDEX IF NOT EXISTS rs_contributions_kind_status_video ON contributions(kind,status,video_id);
CREATE INDEX IF NOT EXISTS rs_performers_status_name ON performers(status,name);
CREATE INDEX IF NOT EXISTS rs_push_subscription_expiry ON push_subscriptions(expires_at);
CREATE INDEX IF NOT EXISTS rs_ratings_video_score ON ratings(video_id,score);
INSERT OR IGNORE INTO state(key,value) VALUES('catalog-revision','0');
CREATE TRIGGER IF NOT EXISTS rs_catalog_videos_insert AFTER INSERT ON videos BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_videos_update AFTER UPDATE ON videos BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_videos_delete AFTER DELETE ON videos BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_matches_insert AFTER INSERT ON matches BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_matches_update AFTER UPDATE ON matches BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_matches_delete AFTER DELETE ON matches BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_channels_insert AFTER INSERT ON channels BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_channels_update AFTER UPDATE ON channels BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_channels_delete AFTER DELETE ON channels BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_performers_insert AFTER INSERT ON performers BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_performers_update AFTER UPDATE ON performers BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_performers_delete AFTER DELETE ON performers BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_exclusions_insert AFTER INSERT ON exclusions BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_exclusions_update AFTER UPDATE ON exclusions BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_exclusions_delete AFTER DELETE ON exclusions BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_runs_insert AFTER INSERT ON runs BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_runs_update AFTER UPDATE ON runs BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_runs_delete AFTER DELETE ON runs BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_snapshot_insert AFTER INSERT ON state WHEN NEW.key >= 'master-' AND NEW.key < 'master.' BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_snapshot_update AFTER UPDATE ON state WHEN NEW.key >= 'master-' AND NEW.key < 'master.' BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
CREATE TRIGGER IF NOT EXISTS rs_catalog_snapshot_delete AFTER DELETE ON state WHEN OLD.key >= 'master-' AND OLD.key < 'master.' BEGIN UPDATE state SET value=CAST(value AS INTEGER)+1 WHERE key='catalog-revision'; END;
