ALTER TABLE runs ADD COLUMN api_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN db_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN duration_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE runs ADD COLUMN records_examined INTEGER NOT NULL DEFAULT 0;
