import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {refreshChannelStats} from '../server/channel-stats.mjs';
import {catalog} from '../server/db.mjs';
function db(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));sql.exec('DELETE FROM channels;');return {prepare(q){let v=[];return {bind(...args){v=args;return this;},async first(){return sql.prepare(q).get(...v)||null;},async all(){return {results:sql.prepare(q).all(...v)};},async run(){return {meta:{changes:Number(sql.prepare(q).run(...v).changes)}};}}},async batch(ss){sql.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const id=n=>'UC'+String(n).padStart(22,'0'),now=new Date('2026-10-06T12:00:00Z');
const fetcher=async url=>Response.json({items:url.searchParams.get('id').split(',').map(id=>({id,snippet:{title:'YouTube name'},statistics:{subscriberCount:'16900',viewCount:'80000',videoCount:'42'}}))});
async function setup(n=1){const d=db();for(let i=1;i<=n;i++)await d.prepare('INSERT INTO channels(id,name) VALUES(?,?)').bind(id(i),'Moderator name').run();return {DB:d,YOUTUBE_API_KEY:'fixture-only'};}
async function stats(env,n=1){return JSON.parse((await env.DB.prepare('SELECT value FROM state WHERE key=?').bind('youtube-channel-stats:'+id(n)).first()).value);}
test('batches 50, skips fresh records, resumes remaining channels, refreshes after 24 hours',async()=>{const e=await setup(51);assert.equal((await refreshChannelStats(e,fetcher,now)).updated,50);assert.equal((await refreshChannelStats(e,fetcher,now)).updated,1);assert.equal((await refreshChannelStats(e,()=>assert.fail('fresh counts must not fetch'),now)).status,'current');assert.equal((await refreshChannelStats(e,fetcher,new Date(+now+86400000))).updated,50);assert.equal((await stats(e)).subscribers,16900);assert.equal((await e.DB.prepare('SELECT name FROM channels WHERE id=?').bind(id(1)).first()).name,'Moderator name');});
test('failure and missing channel preserve last count and back off',async()=>{const e=await setup();await refreshChannelStats(e,fetcher,now);const later=new Date(+now+86400000);const r=await refreshChannelStats(e,async()=>Response.json({error:{errors:[{reason:'quotaExceeded'}]}},{status:403}),later);assert.equal(r.status,'retry');assert.equal((await stats(e)).subscribers,16900);assert.equal((await refreshChannelStats(e,()=>assert.fail('backoff'),later)).status,'current');await refreshChannelStats(e,async()=>Response.json({items:[]}),new Date(+later+3600000));assert.equal((await stats(e)).subscribers,16900);assert.equal((await stats(e)).availability,'unavailable');});
test('hidden count is unknown; catalog overlays stats without changing master snapshots',async()=>{const e=await setup();await e.DB.prepare("INSERT OR REPLACE INTO state(key,value) VALUES(?,?)").bind('master-channel-snapshot:'+id(1),JSON.stringify({id:id(1),name:'Master name',subscribers:100,reactions:7})).run();await refreshChannelStats(e,async()=>Response.json({items:[{id:id(1),statistics:{hiddenSubscriberCount:true}}]}),now);const seed={performers:[{id:'missioned-souls',name:'Missioned Souls'}],channels:[],videos:[]};const c=(await catalog(e.DB,seed,e)).channels.find(c=>c.id===id(1));assert.equal(c.subscribers,null);assert.equal(c.subscribersHidden,true);assert.equal(c.name,'Master name');assert.equal(c.reactions,7);assert.equal(JSON.parse((await e.DB.prepare('SELECT value FROM state WHERE key=?').bind('master-channel-snapshot:'+id(1)).first()).value).subscribers,100);});
test('concurrent invocation is locked and missing key makes no API request',async()=>{const e=await setup();await e.DB.prepare("INSERT INTO state(key,value) VALUES('channel-stats-lock',?)").bind(String(+now+300000)).run();assert.equal((await refreshChannelStats(e,()=>assert.fail('locked'),now)).status,'busy');assert.equal((await refreshChannelStats({DB:e.DB},()=>assert.fail('no key'),now)).status,'blocked');});
