import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {workbookImport,validateImport} from '../server/workbook-import.mjs';
import {workbookPayload} from '../workbook-import-data.mjs';
const channel='UC1234567890123456789012';
function setup(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));
 const db={prepare(q){let values=[];return {bind(...v){values=v;return this;},async first(){return sql.prepare(q).get(...values)||null;},async all(){return {results:sql.prepare(q).all(...values)};},async run(){return {meta:{changes:Number(sql.prepare(q).run(...values).changes)}};}}},async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
 async function call(path,body,user={id:'mod',moderator:true},headers={}){const r=await workbookImport(new Request('https://journey.test/api/workbook-import'+path,{method:body?'POST':'GET',headers:{Origin:'https://journey.test','Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})}),{DB:db},user);return {status:r.status,data:await r.json()};}
 return {sql,call,db};}
function payload(confidence='CONFIRMED'){return {filename:'Master.xlsx',sheet:'Video Import 2026-10-05',channels:[{id:channel,name:'Example reactor'}],videos:[{id:'abcdefghijk',channelId:channel,title:'Missioned Souls reaction',publishedAt:'2026-10-05T12:00:00Z',confidence,format:'FULL_LENGTH'}]};}
test('anonymous and members cannot import; origin and content type are enforced',async()=>{const {call}=setup();assert.equal((await call('/preview',payload(),null)).status,401);assert.equal((await call('/preview',payload(),{id:'fan',moderator:false})).status,403);assert.equal((await call('/preview',payload(),undefined,{Origin:'https://evil.test'})).status,403);assert.equal((await call('/preview',payload(),undefined,{'Content-Type':'text/plain'})).status,415);});
test('preview has no catalog writes; apply is idempotent; probable goes to review',async()=>{const {call,sql}=setup();const p=await call('/preview',payload('PROBABLE'));assert.equal(p.status,200);assert.equal(sql.prepare('SELECT count(*) n FROM videos WHERE id=?').get('abcdefghijk').n,0);assert.equal(p.data.counts.review,1);const r=await call('/apply',{id:p.data.id});assert.equal(r.status,200);assert.equal(r.data.receipt.videos[0].status,'PENDING');assert.equal(sql.prepare('SELECT status FROM matches WHERE video_id=?').get('abcdefghijk').status,'PENDING');assert.equal((await call('/apply',{id:p.data.id})).data.alreadyApplied,true);assert.equal((await call('/history')).data.items[0].status,'applied');});
test('live exclusions and discoveries arriving after preview are rechecked',async()=>{const {call,sql}=setup();const p=await call('/preview',payload());sql.prepare('INSERT OR IGNORE INTO exclusions VALUES(?,?,?)').run('missioned-souls','abcdefghijk','Moderator exclusion');const r=await call('/apply',{id:p.data.id});assert.equal(r.data.receipt.videos[0].disposition,'excluded');assert.equal(sql.prepare('SELECT count(*) n FROM videos WHERE id=?').get('abcdefghijk').n,0);
 sql.prepare('DELETE FROM exclusions WHERE video_id=?').run('abcdefghijk');const p2=await call('/preview',payload());sql.prepare('INSERT INTO videos(id,channel_id,title,format) VALUES(?,?,?,?)').run('abcdefghijk',channel,'Live discovery title','SHORT');sql.prepare('INSERT INTO matches VALUES(?,?,?,?)').run('missioned-souls','abcdefghijk','CONFIRMED','Moderator approval');const r2=await call('/apply',{id:p2.data.id});assert.equal(r2.data.receipt.videos[0].disposition,'existing');assert.equal(sql.prepare('SELECT title,format FROM videos WHERE id=?').get('abcdefghijk').title,'Live discovery title');assert.equal(sql.prepare('SELECT source FROM matches WHERE video_id=?').get('abcdefghijk').source,'Moderator approval');});
test('unavailable videos, channel conflicts, retired channels and locked formats stay protected',async()=>{const {call,sql}=setup();sql.prepare("INSERT OR IGNORE INTO channels(id,name,discovery_scope,checked_at) VALUES(?,?,'retired','previous-scan')").run(channel,'Moderator name');const p=await call('/preview',payload());assert.equal(p.data.counts.videosProtected,1);await call('/apply',{id:p.data.id});assert.equal(sql.prepare('SELECT discovery_scope,name,checked_at FROM channels WHERE id=?').get(channel).discovery_scope,'retired');assert.equal(sql.prepare('SELECT name FROM channels WHERE id=?').get(channel).name,'Moderator name');
 sql.prepare('INSERT OR IGNORE INTO videos(id,channel_id,title,format) VALUES(?,?,?,?)').run('abcdefghijk',channel,'Existing title','SHORT');sql.prepare('DELETE FROM matches WHERE video_id=?').run('abcdefghijk');sql.prepare("UPDATE videos SET available=0,format='SHORT',format_locked=1 WHERE id=?").run('abcdefghijk');const p2=await call('/preview',payload());assert.equal(p2.data.counts.videosProtected,1);await call('/apply',{id:p2.data.id});assert.equal(sql.prepare('SELECT count(*) n FROM matches WHERE video_id=?').get('abcdefghijk').n,0);assert.equal(sql.prepare('SELECT format_locked FROM videos WHERE id=?').get('abcdefghijk').format_locked,1);});
test('other moderators cannot apply private previews; expired previews cannot apply',async()=>{const {call,sql}=setup();const p=await call('/preview',payload());assert.equal((await call('/apply',{id:p.data.id},{id:'other',moderator:true})).status,404);sql.prepare('UPDATE workbook_import_jobs SET created_at=? WHERE id=?').run('2020-01-01',p.data.id);assert.equal((await call('/apply',{id:p.data.id})).status,409);});
test('invalid IDs, conflicting duplicate rows and oversized batches fail validation',()=>{assert.throws(()=>validateImport({...payload(),channels:[{id:'bad',name:'Bad'}]}));assert.throws(()=>validateImport({...payload(),videos:[...payload().videos,{...payload().videos[0],title:'Conflict'}]}));assert.throws(()=>validateImport({...payload(),channels:Array(1001).fill(payload().channels[0])}));});
test('newest sheet selected; rejection/duplicate rows omitted; dates converted as UTC',()=>{const master={sheet:'Updated Master',data:[['Channel ID','Channel Name'],[channel,'Example']]};const headers=['Video ID','Channel ID','Video Title','Classification','Format','Count as Unique','Published UTC'];const old={sheet:'Video Import 2026-09-30',data:[headers]};const latest={sheet:'Video Import 2026-10-05',data:[headers,['abcdefghijk',channel,'Title','CONFIRMED','FULL_LENGTH','TRUE',new Date('2026-10-05T12:00:00Z')],['bcdefghijkl',channel,'Duplicate','REJECTED','FULL_LENGTH','FALSE',null]]};const p=workbookPayload([master,old,latest],'Master.xlsx');assert.equal(p.videos.length,1);assert.equal(p.omitted,1);assert.equal(p.videos[0].publishedAt,'2026-10-05T12:00:00.000Z');});
test('large previews use bounded queries instead of one query per row',async()=>{const {call,db}=setup();let largestBatch=0;const batch=db.batch;db.batch=async statements=>{largestBatch=Math.max(largestBatch,statements.length);return batch(statements);};const p={channels:[],videos:[]};for(let i=0;i<1000;i++){const id='UC'+String(i).padStart(22,'0');p.channels.push({id,name:'Reactor '+i});p.videos.push({id:String(i).padStart(11,'0'),channelId:id,title:'Reaction '+i,publishedAt:null,confidence:'PROBABLE',format:'UNKNOWN'});}const r=await call('/preview',p);assert.equal(r.status,200);assert.equal(r.data.counts.review,1000);assert.ok(largestBatch<=201);assert.equal((await call('/apply',{id:r.data.id})).status,200);});
test('application batch rolls back if any statement fails and can retry safely',async()=>{const {call,db,sql}=setup();const p=await call('/preview',payload());const batch=db.batch;db.batch=statements=>batch([...statements,db.prepare('INSERT INTO nonexistent VALUES(1)')]);assert.equal((await call('/apply',{id:p.data.id})).status,503);assert.equal(sql.prepare('SELECT count(*) n FROM videos WHERE id=?').get('abcdefghijk').n,0);assert.equal(sql.prepare('SELECT status FROM workbook_import_jobs WHERE id=?').get(p.data.id).status,'ready');db.batch=batch;assert.equal((await call('/apply',{id:p.data.id})).status,200);});
