-- October 5 workbook: 410 channels / 34 videos. Explicit application only.
-- Existing rows and moderator decisions are never updated or replaced.
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkcU8Kkqw6pFWRWqKfgDnYw','(701nc)  music reactions / CB radio talk');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCpmNdZS-lEz9Xfaa2XyFX3A','1 1/2 Hours Presents: Adam Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7cJCMIVAWDXgdL8pzqAy6g','2 GEN REACTIONS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBfLiPasLMduGO1FWT9yJ4Q','A Layman''s Reaction');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCUQ4j7ENKEsWkxS_unpv8vw','A''tin Listens');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCulFsMH43Ri5dAh7-UWfKzA','Aaliyah Capili');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSPPu9Ikv66wCWphUH15kog','About Life and Music TV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvp9iUTqyC3Hbnyc4Z4xJlg','Abundance');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCM9jPJf3iQdJgmzgCiXZWQg','Ace of Shaq');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCxVhgUTGnW2vpCoLnJc1lYQ','Ace Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCOfCEZnpmdo5KWkZpcAdUwQ','AceTheHeart');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC954ibeTKDrrz4enROO46gQ','AceTheHeart Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCH98TOIrbPQDjfOXD_zeRrQ','adanne''s family');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCWdO6UC0Nwnm5cLbj0O-yGw','After Dark');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7Hk-H2I2bfXeESTq9r65eA','Agnes is my Dog');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7YiYP8STjAksTomcKmYYxA','Alan - My Musical Journey');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCuhB1xyF_qC6hZMyL8DV3GA','Alex N Channel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCishhr64q7hra4mBVlOO9PA','Alex N Reaction Vault');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCnZtYNtVW9aFc66sxoOQ0RA','Alexa Takes A Look');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSvFrwJOKzk5CuGVS-3Eeyw','Alexander Reaction');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCP-8hOAi0xOykHEZ2PT_QoQ','Alisha & Bee');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDkPNFpl2SiZ5q3Q8fcaVuA','Alizee Defan');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCebfB7LDmATVfTaP2-Q2oDA','ALL GAS NO BREAKS PODCAST');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7fHQIVZtRlIRITZ3SlZWjA','Alpha Wolf Radio With Edygrim DJ');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC3xuaxbfNOHOxDn2DwjD6mg','Amber And Charisse React!');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCH8hJk69WTwScUKGZGbyoMg','AmberVisions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCu2rtkLLCgkLjKKys4JxqOA','Amiekinz4ever');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCF1gJ7i2_tVkefn0w481mNQ','André Santos | Guitarrista');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCe4LiRGr2s2jySDPHQcfXrA','Andrea''s Music Corner');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCb6Gm5wU8Ar6e7R-168Khsw','Andrew Rooney Drums');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCnDuU8yIucgTZ1ouXcm7TTw','Angel D Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMDu1oXiemm1yYWob3nDSeg','Angelina Eonni88');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJFuLZhkoXq7PKDavW10HEQ','Animal Weighs In');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCWre1nDlLE9cE7PdNpi3k9g','AOB The B Side');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCxxt6qt19Gna5C4c9lME9Zw','arty aster');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCWQ-ElaaXR1SeTkw6xrquZw','August Melo');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCAzN5A_zST9aX8IiJ753uCA','B-Drags Den');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCofWn-j1U2gZHosTHH96pfQ','BadBird Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC3xcduJXRL4pGwZ1U_d1cOA','Bane');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC2eXdGwoXGwk9eKTnWxeCSQ','BARS & BARBELLS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRn7ROePUapwmL24LzcEY3A','BassinatorLP');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCqpXbKhNpin0c7hl1NvmoKw','Battoosh & Nonna');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCN6-CkMy_-7t_0wpZnhOAXg','BE4OR');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCM0OKZ9g0wvRdCDCkTj4GFA','Beard Wizard Man');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCb65YCmUB0EwWGo_p9wq4dQ','BeckMax Reacciones');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCI4J8kViQsQMIL-KfbDCFgw','BemusingBill');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClq3l26d0Q18d9nOb61RC1w','Ben Meteor');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCeAf_CPDRtxc_-UPmqzC4Aw','BIGTONYSTV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCTTd4oNtoAUDf-DJTnpPsUQ','Bisscute');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCVdYGxBKxTNLM2nq1_b3V0A','Blattman Presents');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCzgue-_a2KtkpYtgd21_fFg','Bob Cieslinski');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCukx3cpb94uU7mIBWz_4ivA','Bobui Buibo');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSvRaN3v7j5uMf-CWpaQY3w','Brad & Jon React');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCc3FmDyPcAoUq_qmVYfxYXA','Brad Steele');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCOLRLlM0bzSxDioP3nPx9wA','Brandon Faul');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjBsmENliH310wNY36NYcxg','Bruce');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCGJpnw2Or1xNxzWJGsYc-OA','Bruce Deeble');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCsBvvvEvDAypDXTk3HZuZoQ','BTP Gumz TV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCWnDOQoH17R2vDNxiFP-bPg','Burn The Breeze');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC4BLZTtlj1hasWQ1HqJ1ppQ','C&N Podcast');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBoHJ2tc1FvfXqa84WkDcBQ','CamiVocalist');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC75kOrJWOrAdE8MmvbfZFjg','Canal do Chierati');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMBdbblHkPHb5FMCSqXbRSw','CebuAna');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvKSsUSCM1r_8McJwg4kYGQ','Celca React');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjLSPiLvfo-1EDEQamZ87KQ','Chadeo');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7GeuKm8FD5ATbe87P1mPcQ','channel V');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCgOzPhZcicJwSpRQc-cMWDQ','Chelsea Leigh Yogi');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCAichdLjksypfQaPDzopTkQ','Cherman Lang');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvEgHm5bWB8Rvla_Bxl83WA','Cherman Vlogs');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC8xZRLGurUg6UTojwVHADUA','Chilled Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCNvVJj-7YqSV1g042zT-CBA','CHONG REACTS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCetLitg43r0YIGcfid4B8YA','Chords And Notes Nation');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCpwTZxPpGb4vDxUggrVyOQQ','Chris'' Unfiltered Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6y5D__fU6bvebrkV3W8Bmw','Christian Justo Vlogs');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCWvn_CE-8BFkEA04tN5eAfA','Church Boy Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCrztTuQpwd8wNh__4Mu0AEQ','CoachCastTV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCKboltkZSCKZ0olDaaf9ECQ','Cold Fire');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCrmaAG-JUf83AFv8SIdSImA','COM8E Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCtwQvkMG2Ksbe2HhB1WJlOg','Cover Nation');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCL29GEZdmGfYQKwlbmUGsZA','Crazykid949');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCOqvFsE86guyuoi8CxF-k9w','Cryptic Chris');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCY8xhfU0TDowDMY_r5lSUoA','CS 780');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC13-QPy15ywO7InM4XPc35Q','D''N''A');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCLJnnTK_V-dh6wO2cWijdzQ','Daily_music_by_Musa');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6D59ubts04R3lV9NgFuT1g','Dana Nylix');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChsalzGhUr4efWHoJONnJ_g','danebramage 🧠 ROCKS 🤘');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCVtNX9wHTraq3sInjv19WuA','Darth Bane');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCHGGXAyzMMCsuIqwLglUWEQ','Dashy&Dad');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMNI9VvZu0zy4xICGjBJAGQ','Dave M Channel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCpt8oly1SzOabF2gQUboyKQ','Dave Wildheart');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCB8cF_MHSSthyslnfcERdqQ','DaybombTV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCejI9eX8UaTeX-TuHPKNkbw','DEEZY Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCHhpXX300EkRXy1209kx6UQ','Dejesus Dynamics Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7eUtxPy77RqdAQhn6cWa8Q','DFRDiscovers');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCTz4tAUgm367NkgMDjC7dow','Diana B');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCcl6kGS8T1Sy9cAkQnffdMg','Dicodec');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMy9rVGlMvD_Estj3I5OscQ','Did That Really Happen - DTRH');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSNNZk4Q596tigLseZFOl4A','Didi Mark');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC3_54ItQlX75cyxs_2zkkTg','DjB Diwata');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBg9HKuLAop7g5aNKFCn1mg','Double Take Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIBFIha83xPR50EwE_qIkCA','Dr Dan''s Voice Essentials');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCLoUKXR5eqeBjSAIHbY72IQ','Drew Yung');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkuGOvaCzmOUmAmP45_VA7A','Drink The Kool Aid');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCu9W66AgqQsJg-2MEPoxX_w','Driving With Todd');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCAXg-ft7e9JpBlFKrWI2Trg','Drum Attic');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC-WWqxF7LPOssDbasMJyOJg','DrumRoast');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCAKdy3CIb6jn3k_M9gQRbOg','E-Law Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClwQqeaiO38vtrb-FyHZfrg','Enjohns tv');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC2--hembGIwyaMVuhhI0SVw','Erica Reacts - Music & Retro Gaming');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC0qyV-hguga2atlaoL0l2Ag','Erinna_the_White _Rose');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCPghnJ2QlwV1pR693q5F1-Q','Everbright Rachel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC4WzRoZjL4wW6KEp-4psTZw','Everything  Music Theory');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkIKHSr1WfnMdU-_GLTHQpA','FAANA MUSIC');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC9a-HzEGqjhE7v-Hb4F2SNQ','Faustina Mahner');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCzUev9FFU_99TjvVFsUkXtw','FavoriteIslandGirl');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIw3Dm5dfz0JMj5eZeCQ8MQ','Femke Unfiltered');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCTPDIDN7aBE1BB-O7pB6Mmg','FilAm Connections');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC_cGWl4gy-gv8qgo6-IpRTA','FilAmdad');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCknUPsHkzETWQ0wwUO1CpdA','Frad');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCScvZ5GyHVw1CeZtYEwKqFg','FrankValchiria');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC773eBywfxZ0edhQkL7WQrg','G On A Beat');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCnKmvhPS7iNnV14r95Lw22Q','Gavin Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCl_B0xiwmej1pcqVw9W_6Bg','GenX Rock Comeback');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC0fWDW-CjwgYOIWNVWJH0CQ','GeorgeTheCloud');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCiXBlC6KiOcPbS5PSsF2uhA','Gigi Reacts | Lithuanian in the UK');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCZWOGhnKe5lh_KnpNaWRtQg','Ginger T Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvsuX4UcW5WuzZXmmPst76w','GINX Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCq9GKM4Ywp6N3kbjBgUJCMA','Girls Rock Asia');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCwvenK2H-fNo4uUE7SRJL9g','Glasses Kingdom');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC_3I7veV34l3nDT-Lef37Lw','gleen martirezTV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClMb79RC9_r4rIvZZUQ2ftg','Glenn and Adrian''s Rock Talk');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCtwmdPc5rUp2VdJkI2ljH-A','Go Cat Dave - Reaction Videos');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJrfoTTu6ipm-dPuQyHQK1Q','GP42');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChzbdIWMnM01F_MYm8ogbgQ','GREEDY REACTS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCF62YN-9IY0hkCibX0CJ9Ww','Grumpa Mike Radio');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCYIshmP4lgHSrOzX4ubMjPQ','Guitar Lessons and More');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIX9qg7gttMdaSrjnZaC8jg','Guitar Solo Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCuKBVIU5mV2IvyOUBnAuWvw','Hadassah Inspires Us');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC2tM6P9vYB0O9iRGdT9xpDg','Hari Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCNbT6pXIHCD6avCH0WYvQKA','Hawkeye Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCtEs-cB4K1XFnXgLrIWW1Zg','HCJB Music');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCgPEmAm-Vse8CDkdRRu71HA','Hello Brewtiful');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCYeVtkKSZNml2gGePK3YjDg','HEY KANO!');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCl8lWUKCTJsPSO9MHrH5-9Q','Higher Ground Vibes');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDG92z9MZZvu4_Tn0BZCm8g','Hollywood Producers React');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCV5yKBtusZ1wmrPRtehiucg','Honimama 2.0');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCHYoGXkbM5XoR_jXhSFBqtQ','IJayReaction');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCOtztOjWQPgzGaCdtArfWuw','Ije999 Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkpIzIDEgFpUtbmhIrzUsDw','Imraan Arendse Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCnYKHCFmovIlWLgJzsqNhMw','INDIAN REACTION');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjw6Pr8OFYWS2VUvXbxeoqw','ISIBOY');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCyjtZsrZdRO51bb919u2pgQ','ISW Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCs8LEo4k8Ku2MW6VUtlc3cw','ITS EMOTION-O');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCKqxwz5xJoLmgM8n29g8trQ','J Marv');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCgylGj66WQ4awQakoU-LPlg','Jacqueline Van Bierk');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC2qJjs2b-eH7aYiQxaCdViw','Jammer''s Metal Mischief');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCa9GyTms1Kyve7Pyj3i-Vnw','Jason Catron');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7RlFZXw4W-ckvtGf3Ya7qg','JAY WATCH REACTIONS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCGvV9dJ3zhxLcW7LDIMrbTw','Jay Wyatt');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMxEk4S72b57upSJ1xMxt7Q','Jayskii');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCVuxR3SxH7ufkJLa5yerMHw','JennReacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCcq84MkTmI3nX_IBT3WbJ8A','Jenny’s wheel of time 💫');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6svVawMaUfhH45e6hhA7Ow','JESSICA WEST 224');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC752MHKmtEWKUatODPZ5kKw','JFRAGMENT | From Metal to Manila');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChkm9aueQ5uCxfrhVInAztQ','JitteryJay');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjq1ddBxopU2uW7efYz5_9w','JND');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCLKownZBBU-pyuwPzPzfHfQ','Johnny do Carmo');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7JxYkJcB7NNm61Q14HVIBQ','Johnny Foxtrot');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCbcBmBTMsbLxYv-rOyPiRWw','JohnReavesLive');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIB9yrPidvZhW8uf_PT5AtA','Jone Ruiz Guitar');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSKmOZS1SARKI9jTt6GSIcg','Joseph Rocco');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC765pcxZ5vsmiaRg9qMNOGg','JUSTiCE JUNKiES');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJrZMhWnj5z47OOla6QMnHg','JyngerSlapz');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCozLi2EJqC-UO2dx4RceqgA','K17 Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCz-hLsF25Xu8ILLo9twh-9g','KANTA KWENTO');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCz-TAdUNEv1cZXt0_kw8bgg','Kasey Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCxL4e2VMeh1rq1y0J4tv1NA','Kelly''s Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIcyW3hemMJSETDJuIT0pbA','KenMusic');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCwH64yIHQdixU7XUdGRMJ1g','KEVINTY7');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCEI6D-ZJ0rQ4OTW3fZZQj4w','Kiki''s channel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRcnAgWCwVdeGaDxXOStLDA','KJ AVELINO VLOGS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCiE7yuTtYGtVWRvgLGy3_tQ','Kranky Old Dude');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCVNwKCQ6B-4LKKgYQNH-sBg','Kurt De Leon');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCPqxKmmctW6VvJpf3vs-4RQ','Kurtis B.');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCo6VhAuklHvW8ZC35pIezXg','Kyros Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChCKK-iuk-HDrGewri9ouWg','Lanae''s Honest Opinion');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCNj9QC4PsjXOOmTlMwG3nEw','LARIOKE');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIVmJPriTtfAjpY2AM5i0hw','Late Night Reactor');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCGvI6fEHyMnKPuaHlCIB3dw','Laura A. Music Corner');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDDLs7WUrN288iktGODa0yw','LEE REACTS - INFINITE REACTIONS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCPz2QzVLovNkwxKXHyn_7Lw','Legion of Tunes');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCyBK2umOm4MnW0WdwObfZTg','Leo is vibing');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCzKxluCym9y05ZJ-JSaIx_A','Leo Reaccion');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC8QoA0Hk8FAFn2JMSrKIfIg','Life with Steve and Jezie');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCCoRBqjQoglDqcrpg2UqdCA','Lijie');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCQax0riMpFBipXSJhx6AavQ','Lil Kash');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSlY9oi5Ra_poD3D3gK2I0A','Lil mann™ Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCANg-8YEyFpZmI54ALqVcQg','Listen In Colour with Rachel Walker Mason');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7GuAm3U4QK-E3hV98cnHZA','Lito in the Pit');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC_OwIfvGco2rDw8kX8NKg8A','Local Band Smokeout');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCc_C2ZXORZXOG9iVWgGWZLQ','LoccdWolf Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCoWAWe5OXibddW2NYWF6Wgw','LukeTheRed');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC-SkIhoc0hfhvfUh3VRhVSw','lulu');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClzJGBst2_l6pLUlmAv5fWA','Machias Music Man');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCsXpaFizpkib07GojFDAwNQ','Madrix Pit');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCmsFZieFJVO2esvSIvW4F3Q','Mario''s Filipino Channel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCIgxnCASPU5jtdHAMa9YGBg','Marita Arquer');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvVaoyJY997_ApAJpRCe6XQ','Master Reactor');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCOchVS-Nub75s2aaLMRN-IQ','MasterGo');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCgYKdfu_GMWymeuiuo4hijA','MaxStories');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCixS5LJfc-qzAZxzFAYLtwA','McFly JP');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBt8z4eHlqhrysdHgRSmiVA','Melodic Logic');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChTyVmUyLZ8GmeQ-bBxmJQA','Melvin Thinks');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRqJ7AVAuNllkGhjDVez3Hw','MerchantOfAlba');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7lsCbASbTj0qkaoRbLMqGA','Metal Coach Hard Rock and Metal Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCsbiI4XLyrGRUaOEgDIl30g','Metal R Heads Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJv1OxlKhcBHA5QS2TFrf6A','Middle-Aged Mike');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCoEnLUFUY2c8tEM2Glms8Rw','Miggy Boy');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCbYIHB8IhjoOiUTILynsZFA','Mike Mosrie');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC4GqmiZ-Q6_RQNT1DkB5xZg','Mike''s Musical Rehab');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCzwn_DKbKniU7N-I8fgYzGQ','MIRRORGRINN');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRYC6-5K-gpNFS3h6D2T3Ww','MJLimey Reviews All');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMQYQZqpnEkzdr5DA1UzyOg','Modern Life for the 70''s Mind');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC3tmOBoDTaEeHmFb9NDEP1w','Modern Rock Talk');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCmKSX5UfBnxckLdFVrxAtFA','Mom Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCV8aPBobvkyD3AHNqhHYOOg','MommaOG');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJ5uSszZGs8gGy2zqKKzOoQ','monchan54');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6zsSO4MWusVRVvGVt6oraw','Mr. Rock N Roll');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCnJYrL6KJPllz3dF39CtpjA','Mrs. Realistic');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC3qGy9-gqF-jKBstqv5WCWw','MrSammyCam');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCdr9rETIPgmHKq2SgT6WltA','Ms Aina channel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC4vyt2gWjDI-qDY7tq0eg1g','Music and Words Unite');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCwLe_hFre0pBXj4A-segLAA','Music Reactions of the World');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCbUcIZngsYcDTuuwMx_lAsQ','Muzics Reaction');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCEcE-yYEGwtLOTc6VWegGGg','My Catalog');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6gK5d9yDfFNnz6m9K-4_qA','MyIndie Productions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCLDDFkLIkFEcFcDtLf7-qyQ','Nannie''s Take On The World');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC53wjwxrZyoG1w2S3R2PrZw','NAR_by_Marek');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJbbC9LEdWRpXuynPNLqjiQ','Nate Rockne');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCKHG2QhKgActyxTQmbcSPcQ','Nick the Peasant');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCfM46NrCZESnKnOy_aLNFFQ','NicknLex');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC0ffAL5IGWDEMriToPXKQVg','Nina Schofield');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCXj2vn4DScTLfa2Dtw3f5HA','NittPicc');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCncayz8bF4ZFRaY0Oq0WRww','No One Entertainment');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC_OyxffVfDukJPeGfAZ4zPg','Not An industry Artist');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC84p8IUi9tR_1BH_58U14rQ','O melhor da Musica');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkDOHEdOfd6IyaohyRn_vOA','Official-Acquiane-Reaction');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCr32HOUVRuMImkKfbNRZ3CA','OfficialKeeme_Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCAgfypa3N06Vp8nGs1AFngQ','Offset Era (Official Band & Reaction Channel)');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCoJILBuaqBVrFTcHdqm_Lig','OhNoSheDidntReact333');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClTgZzXpcdfrwTLgc4X5bbQ','Ok Here Is The Story');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCi9s1i9ws9CHukbga05vuDg','Ok What''s Next');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCW_rQ0oGBLc7hgcflGXKUmA','Old Mr B');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCE1VGZT42Yk9Ylck9pY1ZcA','Old Phart Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSTuphuOhdBfmIbFC7FJ-8g','One Girl, One Reaction');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCv8D6RWgYu5FydqkNcv9gpg','ONE*A*BEES FAM');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCaqxhpNNqaxscArnufAqxGA','OppositesReact');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvk87FOUye_htA5xMl3GtIQ','Overthinking with Dennis');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjzeCUthjtU3kTvz70sw2wg','P Reacts Daily');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCUwevNkARRcrbq1ghGPGFaw','P Reacts Music');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBR1hhQcznyynuhypN3HTdA','p3cubed');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCl2fC2cHyj_uSNH2mgtQ1nQ','Party Like a Rockstar Podcast');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC_cx4cYXuKfNIG6TEl_Z4sA','Pascal');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCFGAIu7iq2Duubj10Rq6dag','Paul & The Tubies');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClegyeZzlSHbcw5vyAv9OxQ','Peace Beats with Dan Blackwell');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCQfiunkC6t5bguCU8RlMhDA','peniel Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC5JU81qAJKcvPM12Sklb8AQ','Pete Ne Mo Re');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCg9QLq4Mz2zK7tZwMvLcM0A','Pharaoh TV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCrJvtjKiF9ticFEVRTVUfhA','Philiminizzy Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJW4_OuhnlBX5xC2BLjRs0A','Philip Garcia');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCd_k6z99eB0poRf8lUpHMPg','Play It Again with Mike and Ginger');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCwWxpVyRVLhJhLSS1TBVTyw','PopzReacts!!');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCLjqrE8aai5PUDDgTJzKm8Q','Presto Ernesto');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCEWBWHfjngz_g_6LH_A-_BA','Priya Veda Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC34qaPAObd0sg1CTOhLjm3g','Psi & Bella Music');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCppMNpRCT9AkqlRAhbnvd4Q','Radio Teo');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCLdhqd3JAJwzZ0czwgbXPHA','Ramberg Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCR588hWYawFA6vfBSJeyIrA','Ramieh Reacts & Live');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjlsi0ez7tcDDoOXbR_Jh8g','Ravage Mike Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCtDzHr6meh7Y_n6JqSmHazg','Rayactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCwCJVBnaLpI4sTNwcLFH6Cw','RAYGO');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCeRzlB1FBNeJDyjItafm7vw','React and Chill');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCahJtq3gSn-QXXTGzTaj7Fg','Reactions with Vinny');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCCXdo5PHZmlrpo9zAGVx6rA','Reactivity_React');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDs1L2kJBuORMjByOhkAv2w','Reactsbybright');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRp0m1-BiYhBZHlW-8gNbQw','Real Life Couple React');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCKszq-hwLOxdSrXlEHpa91w','redheadedneighbor');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCU9Bx1sRYYJq2oczh9mkA8Q','RedlineReactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDVQQSuvFIFDiuLQpEJF9Yg','Reds AOB (Any Other Business)');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC2ZSncqUXsTEHeS8i8FjnJA','Request Fest Classics');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC-iLo1_6erAtIz3NVqv2qLQ','Retro to Metro Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCzzkTCEHipvlDQMccmID9vQ','Rhythm & Views');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBnVy_XYgikOz3Rqtt7OiUA','Rick G');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCwHEceu0iJDIvhDy6hd0FfQ','Riffs and Reactions With Berry');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCis3h00qcuHn8mtonOdg36A','Rin Situmorang');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCfOmuwwHkq0wbruIT0FdLiQ','RJS_Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJUiNYELU2dGSz_mxd5hJ0A','Rob Simmons');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCug11JLneDcL4NvJdK-3xrg','Robbie Guitar Channel');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRg2we57-t5Igtxh0_9SrPg','Robk Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMHRM06tR8Sa-Hj3yT_k8fQ','Rocío RC Colón');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC9LTz3xthjv3nEjmuTHMssQ','Rock Candy');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCl8rWlxwqaOdRFdL38Ezzew','ROCK ON DUDEZ');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCxoYEzm8zlqksPskfh2FgbQ','Rock Reacts - Pro Singer & Vocal Coach Analysis');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC4C_pHkXtrSrwPILdKsSpZw','Rosalie Elliott');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7Kwbh0a4D4mJUfMYyaQnsQ','rukia dagtan');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCfcKbuwj7AwMh1KBVxvHF7w','Russell Family Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChMzbkGlhqgDvMcP5QnVYeA','Russell Reacts OPM+');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7VK0oV1weNL3E8ClL4zNTg','RVTM REACTS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCS1UK85Gr1_lJ3Fd5G6RZ1g','RVTM: RVZMUSIC');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvKUIZjMmlHJ9vjGJey0SBQ','Ryan Mear');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC27_PpVaZq4kYquM5v0m3lg','S.E.A.T.');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCV15NDUAGGtpcYl0H3pa-Eg','Saeed Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCJNepJEHjqIQgHHTiwfZgeg','SamirReacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCg6cGoIpbqMcA39fcUqaHMg','Sarah Dengler');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCKVxFHlOOt87iUYtp2o18gg','Sarsicles TV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCsHWdTeXelqsJHzTBqz5Meg','Sawyer');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCau87M9DnzSL5iDE9f4uVKQ','Scott And Vivi Couple REACT');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCSJMWK61qhQOfr31p6iyp-w','Sergio Mendes');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCKl8gsoikwaVY8MwERSy8yg','Shirin Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChzBl2DJxKHrErbEj63gBKA','Shut Up Draven');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDUpanoPZcSgTkn9lWb60yA','Sight After Dark');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCjj4fac_cP3kqQ2q3d8zDZA','Sir Mickolas');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCfhqkDIkopvh8dMx70Ej9og','Sohum Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDoBdWeED6dzA3EgvhrcsgA','Son of Buck');
INSERT OR IGNORE INTO channels(id,name) VALUES('UClKbBHrH3SdNcBYpe4Um7aw','Soul Session Sundays');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCQ9x_XFYXL1e3cYyCCe4k2w','Spicy x');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCpeOT68U89Lly1gc8jm4GGg','SpillingTeaWithJaybee Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCqThJgJEu4oGxdGWv93Z3xA','Stev_yt - Reactions & Drumcovers');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCp1dm9SHcmRDLoAjmkY9C7Q','Stratele Studios');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC47fBj1FOPDdXf-HGKejtQg','Street Champs');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC2hAwQ32GJAJuoHV_Smj8Zw','Sunny P');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCYMmkTEKwNoGQuBa2YO-wxQ','Super Sam''s Performance Encore');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCnrukh1IR4xZzBc_5XXiOOw','Swift Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCNZ7Nsfj6cq_FTl-Lq9qlKw','Symaster Mts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCUmqMz8TKx9wLUDbedA5tHg','Talkz2muchOGT');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC-lB_sG0uviaY9pD07kiwjg','Taylor John Hardin Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCuMF9paEZU8RWv9YXd6-rlA','Tazzz Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCdl9f-0AKyQgclcjWPG-0eA','TECKreacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCE1pJWm_D8wOXpHVW052R1g','TeeSpicerReacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7805ONOdUW8AaqjS6wo7VA','Tenor Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6e_cgIkklSLUonsjCc0_og','Tequila Jimmy Unleashed!');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCf5flI2_7HCWNIThWKEEpCw','TEZ REACTIONS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UChPNauUEbb-esCZttccpzSw','The AfterParty Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCrl_6pDCUtaZUpiFyeG4OLQ','The Brothers React');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCuxFu0jLaSGZ0iAEHefSmXw','The Crib Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCVIva9f4cIpZJe2agDF2KpQ','THE EDDIAN PROJECT');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC8ReQVU4PPfbxRy4B18jauw','The Global Take');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkRVcVJTypU020sTrjiiL6g','The Gringa');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCon-nEqPxmXO6pXUU_S5WCg','The Ivy Vibe');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7KATFYYjZG1Zr8eowKdaMQ','The KILLOGIC EFFECT');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCxodpI01GCjP0O1L-LBK8yA','The Mellow Savage');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCTR_PSXLloLzLMBVxnt_kLQ','The Mr. J Show');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC7s59YlBmtABhxFTsRM1ygw','The Naked Truth');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCj3qesaFPaf04pMm58N7G2w','THE NOBODIES REACTS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCXQm2VOsrQlb6BiZdJ33zaQ','The Pentagenarian Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRjC-b3S-AhFRNZrQjAXVGw','The Possibilities Podcast');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC6wVxQeATe3O2XaANCjWFGA','The Rage and The Worst');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCHRdS87_v_yafRqJhXenNlQ','The Real Shakes - P');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC8RVrBdLPB50V1zbci5x7Ng','The Skeptical Hillbilly');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCfQeTYw5jS1UryRg8GN3_PQ','The Smith House Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCFwf5lAecSKl2Dvk7kYcCJQ','The Soulmate Journey');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCm5sIiJYDju4BqDauzbfu6A','The Sound Bus');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCp-pOd2RIxzd04TQ-V0RizQ','The Tightrope to 5D (Music Reactions +)');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCiszHu7E7t5PKprLHACPYqQ','The Tribe Production');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCFD62elPUaYfsj1X5OY1Sdg','The Waking Dreamer');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCxtKLK3DhJ7Z9noOwgYQxkQ','The Waylon Perspective');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCbeFyR4duN97p9pOoFn9aGg','The Wealth Take');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCpw8WBb2MhNMNBNYmwf3mlQ','The Wolf HunterZ');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCDCPjSwCEI1mvxz3TM0MJYw','This is LARIOKE');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC01j-4Q2TUyppuhNJ7pnWdA','Throga - Vocal Gym');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCHxSDK2kjF9zqxPOmYFjB0Q','Tim Overman');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCp9GmsywyVNLdpu8iB0d9Mg','Tim Welch Vocal Studio');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC5b5Mc6rV95hrldFIW78AHg','Toothless Rob');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCBtjFm7bmGzUb3xvYhFSHuQ','Touchy Reactions');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCw1Z_bugtMcWskLnKRjth_A','Tractors & Life');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCP-kGozEU2blvmzI8jNCoKg','Trippin'' With TripleG');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCucnXR4qmpfnEsPUMSnE_Gw','Tristan Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCamo8fs0Vid8msnxc6bOacQ','TRULY ASIA DIARIES');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCPrwKLYGjyw82yJl2BYWFYw','Tunes Brothers');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCsBwg8OaxXyRb5UbpgsIiCg','Twistedshredder');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCw7Mzx9avrOx_6_FSw7uaiQ','TYLR Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCt4pjdGvAmEopu5QQeuSoNA','Unique Guitar World');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCYCpNiKjONodClMP7jqEJNw','UrBFFReacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCTXT5orVqM_ozxatQ-4UO4w','VelcroReacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCfsQSJoU6xcBfn7jkTgAYVQ','VIBE REACTIONS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCkS6l-COP7jAZ_VDp2I2kOQ','Vietnam-era Vet Speaks Out');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCp0tnc7zqsC-Kj74C5oYe-w','Viral Today PH');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMx8QBz4KNo8QouBPJKVEMQ','Vivi’s Take on Today');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCNMu_An-D5cVAxWER3pOfbw','VocalCitizen');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCyPO6t7u2IDYibr8es6BEMw','Volkan Dağcı [Philippines]');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCX7bwcLPagi9x35Q85nPw7A','W & R');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCPAz3hWHiBC-c1x4K0-atsg','Waleska Herrera');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCTs_aBYP6jAF93Cqulq5JIg','Wave Potter');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCmDpLB_c3Dt9hBTQ2DUhQ5w','We Watched That 2');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC17J9qnoQr-IEpONMC5zthQ','Why Am I Reacting');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCRYiATJo58gU-pj82EqubFw','WILBURN MUSIC REACTIONS');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCX17kNr0NElQ18AYt6eqySQ','Wyllow Wisp');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCYRhhAxTdLj2Me5urJz80oQ','Wynand Fourie');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCMlfOZglE_kDc87gwfcdcTg','Xee the World');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC_9tlfrg7umZRU5HHGrBDbQ','Yazik Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCH6XIcx6hQl9Bz2Y41cfb7A','You Made Roskoe');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCmvxS4nuGn4B7TsERoetBpg','Your Online Singing Coach');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCesDxsJL1Ilsf9brQwSctpg','YOUTUNES');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCvDk5Jq1dCrVLCE5yPG5q_g','zach Stephens');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC8SLHBBA-UAM6GNR-z4Lw7A','Zack Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCuXnOFDkPb6HhMpBKfy98Ng','Zaekiro');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCv5YxCx5TOzdGnqjeLTqliw','ZanozClips');
INSERT OR IGNORE INTO channels(id,name) VALUES('UC1eU2jizrLY2Vr0S0lOz8Lg','Zirra Reacts');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCj1RgZ0x6xcsMmBNMZWTyzg','Zooty TV');
INSERT OR IGNORE INTO channels(id,name) VALUES('UCXmTGG_cmVWX-feFTNxWR6Q','ZuluModo Reacts');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'LBSxrD2Jn6I','UCV8aPBobvkyD3AHNqhHYOOg','Missioned Souls - You Give Love a Bad Name (Bon Jovi LIVE Handuraw) | REACTION | First Time Hearing','2026-10-02T17:00:21Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='LBSxrD2Jn6I');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','LBSxrD2Jn6I','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='LBSxrD2Jn6I');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '-oJl3EnNU6Y','UCv5YxCx5TOzdGnqjeLTqliw','Missioned Souls ''TOTAL ECLIPSE OF THE HEART'' by Bonnie Tyler REACTION','2026-10-02T17:06:11Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='-oJl3EnNU6Y');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','-oJl3EnNU6Y','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='-oJl3EnNU6Y');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'mSuKORvscg4','UC84p8IUi9tR_1BH_58U14rQ','VAN HALEN JUMP MISSIONED SOULS COVER ','2026-10-02T22:41:37.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='mSuKORvscg4');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','mSuKORvscg4','PROBABLE','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='mSuKORvscg4');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'ohfKECp-bgo','UCYeVtkKSZNml2gGePK3YjDg','Missioned Souls Brings the EMOTION on “Total Eclipse of the Heart” | Bonnie Tyler Cover Reaction','2026-10-03T00:57:46Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ohfKECp-bgo');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','ohfKECp-bgo','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ohfKECp-bgo');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '0SU_riSmhgQ','UCe4LiRGr2s2jySDPHQcfXrA','The Audience Was Dancing Too?! | Missioned Souls “Twist Again” Reactio','2026-10-03T01:00:17Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='0SU_riSmhgQ');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','0SU_riSmhgQ','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='0SU_riSmhgQ');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '6sPNDhNSD-M','UCY8xhfU0TDowDMY_r5lSUoA','TOTAL ECLIPSE OF THE HEART | Missioned Souls | Reaction','2026-10-03T03:30:32.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='6sPNDhNSD-M');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','6sPNDhNSD-M','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='6sPNDhNSD-M');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'Xob8oY8pCwk','UC5JU81qAJKcvPM12Sklb8AQ','Sweet Child Of Mine - Guns N Roses, Nene Royal & Ozone, Missioned Souls - NeVre reacts','2026-10-03T03:49:16Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='Xob8oY8pCwk');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','Xob8oY8pCwk','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='Xob8oY8pCwk');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'SA0VpQnfDgs','UCr32HOUVRuMImkKfbNRZ3CA','Missioned Souls - TOTAL ECLIPSE OF THE HEART by Bonnie Tyler | Family Band Cover | REACTION 🇯🇲🔥','2026-10-03T05:32:04Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='SA0VpQnfDgs');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','SA0VpQnfDgs','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='SA0VpQnfDgs');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'ZvrQotw0mJ8','UCKl8gsoikwaVY8MwERSy8yg','Missioned Souls -The Winner Takes It All (ABBA)','2026-10-03T07:00:08Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ZvrQotw0mJ8');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','ZvrQotw0mJ8','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ZvrQotw0mJ8');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'XGnRPXlzEuc','UC0fWDW-CjwgYOIWNVWJH0CQ','The 80''s Are In GOOD HANDS! | Missioned Souls – Total Eclipse of the Heart | REACTION','2026-10-03T15:00:06.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='XGnRPXlzEuc');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','XGnRPXlzEuc','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='XGnRPXlzEuc');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'vptNsS-ka_4','UC6y5D__fU6bvebrkV3W8Bmw','TOTAL ECLIPSE OF THE HEART by Band Studio CoverBonnie Tyler | Missioned Souls | Family | REACTION','2026-10-03T17:37:52.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='vptNsS-ka_4');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','vptNsS-ka_4','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='vptNsS-ka_4');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '1Zo0Z-OIvMQ','UCzUev9FFU_99TjvVFsUkXtw','TOTAL ECLIPSE OF THE HEART by Bonnie Tyler Missioned Souls Family Band Studio Cover REACTION','2026-10-03T19:22:18Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='1Zo0Z-OIvMQ');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','1Zo0Z-OIvMQ','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='1Zo0Z-OIvMQ');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'uYE0EbHiP14','UCNbT6pXIHCD6avCH0WYvQKA','TOTAL ECLIPSE OF THE HEART by Bonnie Tyler | Missioned Souls | Family Band Studio Cover - REACTION','2026-10-03T20:00:13.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='uYE0EbHiP14');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','uYE0EbHiP14','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='uYE0EbHiP14');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'jdUudzKahQw','UC84p8IUi9tR_1BH_58U14rQ','Starship (nothing''s gonna stop us now) Missioned Souls Cover Band.','2026-10-03T23:42:13.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='jdUudzKahQw');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','jdUudzKahQw','PROBABLE','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='jdUudzKahQw');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'lNm6xp81zVk','UC7YiYP8STjAksTomcKmYYxA','MISSIONED SOULS — “ALL IT TAKES” | THEIR OWN SONG AT LAST {FIRST REACTION}','2026-10-04T04:00:28Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='lNm6xp81zVk');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','lNm6xp81zVk','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='lNm6xp81zVk');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'xFdc2K4bhRQ','UC5JU81qAJKcvPM12Sklb8AQ','My Hero - Foo Fighters ft Shane Hawkins, Missioned Souls - NeVre reacts','2026-10-04T04:53:13Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='xFdc2K4bhRQ');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','xFdc2K4bhRQ','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='xFdc2K4bhRQ');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '8uoPfz30JoE','UCo6VhAuklHvW8ZC35pIezXg','Reacting to Missioned Souls | Total Eclipse of The Heart','2026-10-04T06:00:26Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='8uoPfz30JoE');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','8uoPfz30JoE','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='8uoPfz30JoE');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'ZzrTBxg3AZs','UCz-hLsF25Xu8ILLo9twh-9g','Neisha Best of the Best Guitar ever in the history #missionedsouls #familyband #kantakwento','2026-10-04T07:00:26Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ZzrTBxg3AZs');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','ZzrTBxg3AZs','PROBABLE','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ZzrTBxg3AZs');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '5EKyuywCVN0','UClMb79RC9_r4rIvZZUQ2ftg','Musicians REACT to Missioned Souls: Total Eclipse of the Heart (2026 Bonnie Tyler cover)','2026-10-04T10:00:37Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='5EKyuywCVN0');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','5EKyuywCVN0','PROBABLE','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='5EKyuywCVN0');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'lurboAHW7nA','UCkcU8Kkqw6pFWRWqKfgDnYw','Missioned Souls- covering Long Time by Boston!!!!!!!','2026-10-04T11:57:26Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='lurboAHW7nA');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','lurboAHW7nA','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='lurboAHW7nA');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'Bm_Xvy_mLzI','UCRn7ROePUapwmL24LzcEY3A','[REACTION] Missioned Souls in Zambales | Smoke on the water - Live cover','2026-10-04T12:00:30Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='Bm_Xvy_mLzI');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','Bm_Xvy_mLzI','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='Bm_Xvy_mLzI');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'G642cQVcb1o','UCf5flI2_7HCWNIThWKEEpCw','MISSIONED SOULS SAID LETS DO JUSTICE TO THAT PIANO SOLO!!! JUMP COVER REACTION','2026-10-04T12:10:58Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='G642cQVcb1o');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','G642cQVcb1o','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='G642cQVcb1o');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'fuSVdbtSPmo','UCH8hJk69WTwScUKGZGbyoMg','Missioned Souls – “What I’ve Done” Linkin Park Cover | FIRST REACTION','2026-10-04T13:14:52Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='fuSVdbtSPmo');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','fuSVdbtSPmo','PROBABLE','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='fuSVdbtSPmo');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'kH6vzMgvfS0','UCRYiATJo58gU-pj82EqubFw','THIS 11 YEAR OLD DRUMMER IS UNREAL - MISSIONED SOULS','2026-10-04T16:30:28Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='kH6vzMgvfS0');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','kH6vzMgvfS0','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='kH6vzMgvfS0');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'GqR0etTVgLo','UCkuGOvaCzmOUmAmP45_VA7A','Missioned Souls "SWEET CHILD O'' MINE" Reaction: Can a 15-Year-Old Really Play Slash''s Solo? ⭐','2026-10-04T23:00:05Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='GqR0etTVgLo');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','GqR0etTVgLo','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='GqR0etTVgLo');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'L1Mjigpg_9Q','UCP-kGozEU2blvmzI8jNCoKg','Missioned Souls – Total Eclipse of the Heart | They Said Bring Tissues… NEISHA! 😂','2026-10-04T23:00:39Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='L1Mjigpg_9Q');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','L1Mjigpg_9Q','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='L1Mjigpg_9Q');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'ZwRagOr7PYQ','UC5JU81qAJKcvPM12Sklb8AQ','All It Takes - Missioned Souls - NeVre reacts','2026-10-05T01:25:02Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ZwRagOr7PYQ');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','ZwRagOr7PYQ','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='ZwRagOr7PYQ');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'DgoMTT9k3zc','UC6gK5d9yDfFNnz6m9K-4_qA','MISSIONED SOULS - ALL IT TAKES (OMV) reaction by Indie Filmmakers 🔥🔥🔥 #banger #familyband #original','2026-10-05T03:21:50Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='DgoMTT9k3zc');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','DgoMTT9k3zc','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='DgoMTT9k3zc');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'aneKwo8mgoM','UC4GqmiZ-Q6_RQNT1DkB5xZg','Missioned Souls Cover TOTAL ECLIPSE OF THE HEART – THIS Was Incredible!','2026-10-05T04:00:11Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='aneKwo8mgoM');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','aneKwo8mgoM','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='aneKwo8mgoM');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'pAGYT3pmWMU','UC5JU81qAJKcvPM12Sklb8AQ','Rosanna - Toto, Missioned Souls - NeVre reacts','2026-10-05T04:58:04.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='pAGYT3pmWMU');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','pAGYT3pmWMU','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='pAGYT3pmWMU');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'M-9Ax0N3dBk','UC6zsSO4MWusVRVvGVt6oraw','Fogerty Smiling Again!! | CCR - Bad Moon Rising | Missioned Souls | Family Cover | REACTION','2026-10-05T15:30:44Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='M-9Ax0N3dBk');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','M-9Ax0N3dBk','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='M-9Ax0N3dBk');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'e2z_G7KU1o8','UCaqxhpNNqaxscArnufAqxGA','Missioned Souls (LIVE) - Hysteria - American Sisters Blind React!!','2026-10-05T16:00:31.999000Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='e2z_G7KU1o8');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','e2z_G7KU1o8','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='e2z_G7KU1o8');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT '6DHGU_46BZ0','UCDVQQSuvFIFDiuLQpEJF9Yg','Red Reacts | Reaction To Missioned Souls | TOTAL ECLIPSE OF THE HEART (Bonnie Tyler)','2026-10-05T17:00:16Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='6DHGU_46BZ0');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','6DHGU_46BZ0','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='6DHGU_46BZ0');
INSERT OR IGNORE INTO videos(id,channel_id,title,published_at,discovered_at,format) SELECT 'vZU-MeRiTmg','UCbYIHB8IhjoOiUTILynsZFA','🎸 Bad Moon Rising by Creedence Clearwater Revival | Missioned Souls | Family Band Cover Reaction','2026-10-05T19:25:04Z','2026-10-05T21:58:00Z','FULL_LENGTH' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='vZU-MeRiTmg');
INSERT OR IGNORE INTO matches(performer_id,video_id,status,source) SELECT 'missioned-souls','vZU-MeRiTmg','CONFIRMED','Master reconciliation 2026-10-05; search-results-only evidence' WHERE NOT EXISTS (SELECT 1 FROM exclusions WHERE performer_id='missioned-souls' AND video_id='vZU-MeRiTmg');
