import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const performers = sqliteTable('performers', { id: text('id').primaryKey(), name: text('name').notNull(), aliases: text('aliases').notNull(), officialUrl:text('official_url'), status:text('status').notNull().default('active'), reviewMode:text('review_mode').notNull().default('auto'), lookbackDays:integer('lookback_days').notNull().default(30), discoveryEnabled:integer('discovery_enabled').notNull().default(1), chatEnabled:integer('chat_enabled').notNull().default(1), updatedAt:text('updated_at') });
export const channels = sqliteTable('channels', { id: text('id').primaryKey(), name: text('name').notNull(), uploads: text('uploads'), checkedAt: text('checked_at'), nextPage: text('next_page'), scanBefore: text('scan_before'), scanStarted: text('scan_started') });
export const videos = sqliteTable('videos', { id: text('id').primaryKey(), channelId: text('channel_id').notNull(), title: text('title').notNull(), publishedAt: text('published_at'), discoveredAt: text('discovered_at'), checkedAt: text('checked_at'), format: text('format').notNull().default('UNKNOWN'), available: integer('available').notNull().default(1) });
export const matches = sqliteTable('matches', { performerId: text('performer_id').notNull(), videoId: text('video_id').notNull(), status: text('status').notNull(), source: text('source').notNull() }, t => [primaryKey({ columns: [t.performerId, t.videoId] })]);
export const exclusions = sqliteTable('exclusions', { performerId: text('performer_id').notNull(), videoId: text('video_id').notNull(), reason: text('reason').notNull() }, t => [primaryKey({ columns: [t.performerId, t.videoId] })]);
export const runs = sqliteTable('runs', { id: text('id').primaryKey(), startedAt: text('started_at').notNull(), finishedAt: text('finished_at'), status: text('status').notNull(), calls: integer('calls').notNull().default(0), channels: integer('channels').notNull().default(0), added: integer('added').notNull().default(0), detail: text('detail') }, t => [index('runs_started').on(t.startedAt)]);
export const state = sqliteTable('state', { key: text('key').primaryKey(), value: text('value').notNull() });
export const members = sqliteTable('members', { id: text('id').primaryKey(), name: text('name').notNull(), createdAt: text('created_at').notNull(), profileIcon:text('profile_icon').notNull().default('initials'), profileColor:text('profile_color').notNull().default('teal'), profilePicture:text('profile_picture'), trusted:integer('trusted').notNull().default(0), trustReviewedAt:text('trust_reviewed_at') },t=>[index('member_trust_status').on(t.trusted,t.trustReviewedAt)]);
export const ratings = sqliteTable('ratings', { userId: text('user_id').notNull().references(()=>members.id), videoId: text('video_id').notNull().references(()=>videos.id), score: integer('score').notNull(), createdAt: text('created_at').notNull() }, t=>[primaryKey({columns:[t.userId,t.videoId]}),index('ratings_video').on(t.videoId)]);
export const contributions = sqliteTable('contributions', { id:text('id').primaryKey(), userId:text('user_id').notNull().references(()=>members.id), kind:text('kind').notNull(), performerId:text('performer_id').notNull().references(()=>performers.id), videoId:text('video_id').notNull(), channelId:text('channel_id').references(()=>channels.id), body:text('body').notNull(), parentId:text('parent_id'), reason:text('reason'), status:text('status').notNull().default('pending'), createdAt:text('created_at').notNull(), reviewedAt:text('reviewed_at'), reviewedBy:text('reviewed_by'), reviewNote:text('review_note') }, t=>[index('contributions_queue').on(t.status,t.createdAt),index('contributions_user_date').on(t.userId,t.createdAt),index('contributions_video').on(t.videoId,t.kind,t.status),index('contributions_channel').on(t.channelId,t.kind,t.status,t.createdAt)]);
export const points = sqliteTable('points', { id:text('id').primaryKey(), userId:text('user_id').notNull().references(()=>members.id), kind:text('kind').notNull(), amount:integer('amount').notNull(), createdAt:text('created_at').notNull() },t=>[index('points_user_date').on(t.userId,t.createdAt)]);
export const preferences = sqliteTable('preferences',{userId:text('user_id').primaryKey(),settings:text('settings').notNull(),updatedAt:text('updated_at').notNull()});
export const savedViews = sqliteTable('saved_views',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),settings:text('settings').notNull(),createdAt:text('created_at').notNull()},t=>[index('views_user').on(t.userId)]);
export const follows = sqliteTable('follows',{userId:text('user_id').notNull(),kind:text('kind').notNull(),target:text('target').notNull()},t=>[primaryKey({columns:[t.userId,t.kind,t.target]})]);
export const watch = sqliteTable('watch',{userId:text('user_id').notNull(),videoId:text('video_id').notNull(),status:text('status').notNull(),favorite:integer('favorite').notNull().default(0)},t=>[primaryKey({columns:[t.userId,t.videoId]})]);
export const commentLikes = sqliteTable('comment_likes',{userId:text('user_id').notNull(),commentId:text('comment_id').notNull()},t=>[primaryKey({columns:[t.userId,t.commentId]})]);
export const blocks = sqliteTable('blocks',{userId:text('user_id').notNull(),target:text('target').notNull()},t=>[primaryKey({columns:[t.userId,t.target]})]);
export const chatMessages = sqliteTable('chat_messages',{id:text('id').primaryKey(),room:text('room').notNull(),userId:text('user_id').notNull(),body:text('body').notNull(),status:text('status').notNull().default('visible'),createdAt:text('created_at').notNull()},t=>[index('chat_room_date').on(t.room,t.createdAt),index('chat_user_date').on(t.userId,t.createdAt)]);
export const roomMembers = sqliteTable('room_members',{userId:text('user_id').notNull(),room:text('room').notNull(),lastRead:text('last_read').notNull(),seenAt:text('seen_at').notNull()},t=>[primaryKey({columns:[t.userId,t.room]})]);
export const mutes = sqliteTable('mutes',{userId:text('user_id').primaryKey(),until:text('until').notNull(),reason:text('reason').notNull()});
export const abuseReports = sqliteTable('abuse_reports',{id:text('id').primaryKey(),userId:text('user_id').notNull(),kind:text('kind').notNull(),target:text('target').notNull(),body:text('body').notNull(),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull()},t=>[index('abuse_status').on(t.status)]);
export const reputationEvents = sqliteTable('reputation_events',{id:text('id').primaryKey(),userId:text('user_id').notNull(),amount:integer('amount').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[index('reputation_user').on(t.userId)]);
export const coverageRequests = sqliteTable('coverage_requests',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>members.id),name:text('name').notNull(),nameKey:text('name_key').notNull(),performerId:text('performer_id'),url:text('url').notNull(),body:text('body').notNull(),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull(),reviewedAt:text('reviewed_at'),reviewedBy:text('reviewed_by'),reviewNote:text('review_note')},t=>[index('coverage_queue').on(t.status,t.createdAt),index('coverage_user').on(t.userId,t.createdAt)]);

export const pushSubscriptions = sqliteTable('push_subscriptions',{channelId:text('channel_id').primaryKey(),secret:text('secret').notNull(),token:text('token').notNull(),callback:text('callback').notNull(),requestedAt:text('requested_at').notNull(),pendingUntil:integer('pending_until').notNull(),expiresAt:integer('expires_at').notNull().default(0),error:text('error')});
export const pushJobs = sqliteTable('push_jobs',{source:text('source').notNull().default('YouTube upload notification'),videoId:text('video_id').primaryKey(),channelId:text('channel_id').notNull(),receivedAt:text('received_at').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0),processedAt:text('processed_at'),error:text('error')},t=>[index('push_jobs_due').on(t.status,t.nextAttempt)]);
export const discoveryNotifications = sqliteTable('discovery_notifications',{performerId:text('performer_id').notNull(),videoId:text('video_id').notNull(),createdAt:text('created_at').notNull(),source:text('source').notNull(),status:text('status').notNull().default('new'),reviewedAt:text('reviewed_at'),reviewedBy:text('reviewed_by'),note:text('note')},t=>[primaryKey({columns:[t.performerId,t.videoId]}),index('discovery_notifications_status').on(t.status,t.createdAt)]);

export const profilePictures=sqliteTable('profile_pictures',{id:text('id').primaryKey(),userId:text('user_id').notNull().unique().references(()=>members.id),data:text('data').notNull()});

export const rssChecks=sqliteTable('rss_checks',{channelId:text('channel_id').primaryKey(),checkedAt:text('checked_at').notNull(),retryAt:text('retry_at'),error:text('error')},t=>[index('rss_checks_date').on(t.checkedAt)]);
export const notificationReceipts=sqliteTable('notification_receipts',{videoId:text('video_id').notNull(),source:text('source').notNull(),receivedAt:text('received_at').notNull(),processedAt:text('processed_at')},t=>[primaryKey({columns:[t.videoId,t.source]}),index('notification_receipts_date').on(t.receivedAt)]);

export const memberTrustHistory=sqliteTable('member_trust_history',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>members.id),moderatorId:text('moderator_id'),trusted:integer('trusted').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[index('member_trust_history_user').on(t.userId,t.createdAt)]);
